### PR TITLE
GH-3855 changeset performance

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3855 

Briefly describe the changes proposed in this PR:

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra it seems that new default methods in an interface are not binary compatible. We used to allow this for minor releases (eg. 4.1.0).

**Comment by jeenbroekstra** [comment]
I think we need to have a wider discussion about what kind of compatibility we want to support. Possibly binary is not really preferred for minor releases in general, only for patches....

**Comment by jeenbroekstra** [comment]
We can tweak this how we like, I just went with the defaults assuming that's reflecting the widest concensus on what SemVer entails.

**Comment by hmottestad** [comment]
At the moment I haven't found any existing benchmarks that are improved in this branch. The changes are based on my WIP performance branch #3854. Fixing one bottle neck will often reveal another performance issue that was masked by the initial bottle neck, so that might be the case here too. That being said there are quite a few fixes in that branch that didn't end up making much of a difference.

**Comment by hmottestad** [comment]
### Before
```

```

### After
```
Benchmark                                                                   Mode  Cnt     Score   Error  Units
ParallelBenchmark.nativeStoreShaclSerializable                              avgt       1065.466          ms/op
ParallelBenchmark.nativeStoreShaclSerializableNotParallel                   avgt         84.068          ms/op
ParallelBenchmark.nativeStoreShaclSnapshot                                  avgt         94.863          ms/op
ParallelBenchmark.nativeStoreShaclSnapshotWithoutSerializableValidation     avgt         86.315          ms/op
ParallelBenchmark.shaclSerializable                                         avgt         40.748          ms/op
ParallelBenchmark.shaclSerializableMixedReadWrite                           avgt         59.509          ms/op
ParallelBenchmark.shaclSerializableNotParallel                              avgt         24.996          ms/op
ParallelBenchmark.shaclSnapshot                                             avgt         13.425          ms/op
ParallelBenchmark.shaclSnapshotMixedReadWrite                               avgt         18.305          ms/op
ParallelBenchmark.shaclSnapshotWithoutSerializableValidation                avgt          8.128          ms/op
ParallelBenchmark.shaclSnapshotWithoutSerializableValidationMixedReadWrite  avgt         16.420          ms/op
```

**Comment by hmottestad** [comment]
### Before
Screenshot 2022-05-31 at 11 04 30

### After
Screenshot 2022-05-31 at 11 05 40

**Pull request merged**
