### PR TITLE
GH-1942 Made sure all character format writers have Writer constructor

### PR DESCRIPTION
**Pull request by erikgb**
GitHub issue (partly) resolved: #1942

Briefly describe the changes proposed in this PR:

- Added `Writer` constructors to all character format `QueryResultWriter` classes
- Consistent handling of `Writer` (or `Writer` based) fields from `OutputStream` and `Writer` constructors in `QueryResultWriter` and `RDFWriter` classes

---- 
PR Author Checklist: 

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
I've changed the target branch to develop because this is a new feature, rather than a bug fix. Unfortunately it seems to cause conflicts (we did do some other work on the rio writers in develop). @erikgb are you available to look into those conflicts and resolve them? If not I can take a look, too.

**Comment by erikgb** [comment]
@jeenbroekstra: Resolving the conflicts is possible, but there is a change performed on the develop branch that makes my change hard to implement correctly, I think. What should I do with the `outputStream` field added to the abstract superclasses when a Writer constructor has been invoked on a subclass? What is really the purpose of this new optional `outputStream` field?

I think that adding new Writer constuctors is now not advisable, and definitely not a new setting for the writer character encoding. There is just too much state to handle correctly - with the state introduced in the abstract superclasses.

In general I try to avoid _implementation_ (abstract class) inheritance. The class hierarchies tends to get bloated by it... One thing I noticed: Did you forget the `N3Writer` class when introducing the new `getOutputStream` method on `RDFWriter`? It does not extend `AbstractRDFWriter`....

Please advice...

**Comment by jeenbroekstra** [comment]
Oh dear. Let me take a closer look, I think we added this as part of GH-400 which needed to be able to retrieve the outputstream from the writer, if available.

**Comment by jeenbroekstra** [comment]
@erikgb I've pushed a merge conflict fix to your branch that takes care of the immediate issue. I do think that we'll want to revisit GH-400 at some point, because I'm not really happy with the situation where we keep track of both an OutputStream _and_ a Writer object. But fixing that is beyond the scope of what you're trying to do here I think.

**Comment by jeenbroekstra** [comment]
Oh and one more request: could we have one or two test cases that verify using these writers with non-default charsets works as expected?

**Comment by erikgb** [comment]
@jeenbroekstra: Regarding #1943, I did not like the solution either. 😉 Not just because it created problems for me, but introducing additional (optional) state tends to lead to problems down the line. I looked a bit at the changes and the originating issue. Could we borrow some design from [Guava ByteSink](https://guava.dev/releases/snapshot/api/docs/com/google/common/io/ByteSink.html) to achieve the wanted stream passthrough? In particular the `ByteSink#writeFrom(InputStream)` method, which in this case could be used to pass the response `InputStream` to the writer. This design can potentially be a good starting point for writers being generally able to deal with "raw" RDF data (bytes).

If we wanted to take this even further, the writers could be classified as either a "ByteSink" or a "CharSink" - which could make a lot of sense. A writer format is either character based or binary.

**Comment by erikgb** [comment]
> Oh and one more request: could we have one or two test cases that verify using these writers with non-default charsets works as expected?

Yes, I will try to add some tests to test the currently unused Writer constructors.

**Comment by jeenbroekstra** [comment]
> Could we borrow some design from Guava ByteSink to achieve the wanted stream passthrough? In particular the ByteSink#writeFrom(InputStream) method, which in this case could be used to pass the response InputStream to the writer. This design can potentially be a good starting point for writers being generally able to deal with "raw" RDF data (bytes).

I was thinking of a simpler approach, just getting rid of keeping a reference to the outputstream, and just having each writer keep an internal java.io.Writer object. The constructor with outputstream could just wrap the outputstream in a writer. 

But I'm happy to hear plans for a more comprehensive redesign, sounds intriguing. Perhaps open a new issue ticket to discuss?

**Comment by jeenbroekstra** [comment]
@erikgb we are getting close to our deadline for the 3.2.0 release (basically, this Thursday). Are you still planning to push those tests we discussed? No problem if you can't, but I'll need to make a judgment call on whether we include this improvement in the release or not by Wednesday.

**Comment by erikgb** [comment]
> Are you still planning to push those tests we discussed? No problem if you can't, but I'll need to make a judgment call on whether we include this improvement in the release or not by Wednesday.

@jeenbroekstra I am trying to move forward on the tests, but my gut feeling tells me that we should not try to "push" immature things into upcoming releases. No rush from my point of view, and there has been quite a few changes on the develop branch in this area, so I am suggesting to postpone this PR to a future minor/major release.

**Comment by jeenbroekstra** [comment]
Quite agree. Fwiw I will be marking that new `getOutputStream` method in RDFWriter experimental / for internal use only. This gives us some leeway to adapt the design later without having to worry about backward compatibility.

**Comment by jeenbroekstra** [comment]
Did we close this by accident?

**Comment by hmottestad** [comment]
It says I closed it. But I didn't do that on purpose at least. Sorry.

**Comment by jeenbroekstra** [comment]
No worries, happens to the best of us ;)

**Comment by hmottestad** [comment]
@jeenbroekstra did you close this intentionally?

**Comment by jeenbroekstra** [comment]
No. Very odd. I don't remember even looking at this PR today, let alone accidentally closing it.

**Comment by jeenbroekstra** [comment]
Ah, hang on I think I know what happened. When I merged develop into master for the 3.4 release, the develop branch automatically got deleted. I restored it, but I think Github automatically closes any pull request that targets a closed branch. 

There may be a few other PRs that we'll need to restore.

**Comment by jeenbroekstra** [comment]
I am merging this PR into a new feature branch in our core repository. This will allow me a little more leeway in updating this work to resolve conflicts (including rebasing) and getting it to a release-ready state.

**Pull request merged**
