### PR TITLE
GH-3789 RDFS Reasoner Challenge fixes

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3789  

Briefly describe the changes proposed in this PR:

 - logging
 - support isolation level NONE
 - improve performance
 - fix flushing of inferred statements in the NativeStore
 - concurrent forward chaining

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
```
09:09:32.294 [main] DEBUG Calculate inference maps.
09:09:32.294 [main] DEBUG Calculate rdfs:subClassOf inference map.
09:09:32.294 [main] DEBUG Fill initial maps
09:09:32.295 [main] DEBUG Run until fixed point
09:09:32.296 [main] DEBUG Fixed point iteration new size 31
09:09:32.297 [main] DEBUG Fixed point iteration new size 31
09:09:32.298 [main] DEBUG Calculate rdfs:subPropertyOf inference map.
09:09:32.298 [main] DEBUG Run until fixed point
09:09:32.299 [main] DEBUG Fixed point iteration new size 17
09:09:32.299 [main] DEBUG Fixed point iteration new size 17
09:09:32.299 [main] DEBUG Calculate rdfs:domain and rdfs:range inference map.
09:09:32.299 [main] DEBUG Run until fixed point
09:09:32.300 [main] DEBUG Fixed point iteration new size 24
09:09:32.300 [main] DEBUG Fixed point iteration new size 24
09:09:32.300 [main] DEBUG Calculate rdfs:domain and rdfs:range inference map.
09:09:32.301 [main] DEBUG Run until fixed point
09:09:32.301 [main] DEBUG Fixed point iteration new size 25
09:09:32.301 [main] DEBUG Fixed point iteration new size 25
09:09:32.301 [main] DEBUG Add inferred rdfs:subClassOf statements
09:09:32.301 [main] DEBUG Add inferred rdfs:subPropertyOf statements
09:09:32.302 [main] DEBUG Flush updates
09:09:32.302 [main] DEBUG Do inferencing
09:09:32.302 [main] DEBUG Regenerate cache and inference maps
09:09:32.302 [main] DEBUG Clear inference tables
09:09:32.308 [main] DEBUG Calculate inference maps.
09:09:32.308 [main] DEBUG Calculate rdfs:subClassOf inference map.
09:09:32.308 [main] DEBUG Fill initial maps
09:09:32.308 [main] DEBUG Run until fixed point
09:09:32.308 [main] DEBUG Fixed point iteration new size 31
09:09:32.308 [main] DEBUG Fixed point iteration new size 31
09:09:32.308 [main] DEBUG Calculate rdfs:subPropertyOf inference map.
09:09:32.308 [main] DEBUG Run until fixed point
09:09:32.308 [main] DEBUG Fixed point iteration new size 17
09:09:32.308 [main] DEBUG Fixed point iteration new size 17
09:09:32.308 [main] DEBUG Calculate rdfs:domain and rdfs:range inference map.
09:09:32.308 [main] DEBUG Run until fixed point
09:09:32.308 [main] DEBUG Fixed point iteration new size 24
09:09:32.308 [main] DEBUG Fixed point iteration new size 24
09:09:32.308 [main] DEBUG Calculate rdfs:domain and rdfs:range inference map.
09:09:32.308 [main] DEBUG Run until fixed point
09:09:32.309 [main] DEBUG Fixed point iteration new size 25
09:09:32.309 [main] DEBUG Fixed point iteration new size 25
09:09:32.309 [main] DEBUG Add inferred rdfs:subClassOf statements
09:09:32.309 [main] DEBUG Add inferred rdfs:subPropertyOf statements
09:09:32.310 [main] DEBUG Forward chain all explicit statements
09:09:32.310 [main] DEBUG Inferencing complete
Add abox
Add tbox
Commit
09:09:46.089 [main] DEBUG Flush updates
09:09:46.089 [main] DEBUG Do inferencing
09:09:46.089 [main] DEBUG Regenerate cache and inference maps
09:09:46.089 [main] DEBUG Clear inference tables
09:09:48.053 [main] DEBUG Calculate inference maps.
09:09:48.053 [main] DEBUG Calculate rdfs:subClassOf inference map.
09:09:48.053 [main] DEBUG Fill initial maps
09:09:49.873 [main] DEBUG Run until fixed point
09:09:52.032 [main] DEBUG Fixed point iteration new size 18754664
09:09:59.443 [main] DEBUG Fixed point iteration new size 59096739
09:10:16.703 [main] DEBUG Fixed point iteration new size 74328011
09:10:35.668 [main] DEBUG Fixed point iteration new size 74462719
09:10:53.653 [main] DEBUG Fixed point iteration new size 74462719
09:10:53.655 [main] DEBUG Calculate rdfs:subPropertyOf inference map.
09:10:53.655 [main] DEBUG Run until fixed point
09:10:53.656 [main] DEBUG Fixed point iteration new size 1440
09:10:53.657 [main] DEBUG Fixed point iteration new size 1440
09:10:53.657 [main] DEBUG Calculate rdfs:domain and rdfs:range inference map.
09:10:53.657 [main] DEBUG Run until fixed point
09:10:53.659 [main] DEBUG Fixed point iteration new size 32
09:10:53.660 [main] DEBUG Fixed point iteration new size 32
09:10:53.660 [main] DEBUG Calculate rdfs:domain and rdfs:range inference map.
09:10:53.660 [main] DEBUG Run until fixed point
09:10:53.661 [main] DEBUG Fixed point iteration new size 32
09:10:53.661 [main] DEBUG Fixed point iteration new size 32
09:10:53.662 [main] DEBUG Add inferred rdfs:subClassOf statements
09:10:54.458 [main] DEBUG Added 1000000 inferred statements
09:10:55.291 [main] DEBUG Added 2000000 inferred statements
09:10:56.128 [main] DEBUG Added 3000000 inferred statements
09:10:56.916 [main] DEBUG Added 4000000 inferred statements
09:10:57.771 [main] DEBUG Added 5000000 inferred statements
09:10:58.830 [main] DEBUG Added 6000000 inferred statements
09:10:59.795 [main] DEBUG Added 7000000 inferred statements
09:11:00.808 [main] DEBUG Added 8000000 inferred statements
09:11:01.779 [main] DEBUG Added 9000000 inferred statements
09:11:02.649 [main] DEBUG Added 10000000 inferred statements
09:11:03.537 [main] DEBUG Added 11000000 inferred statements
09:11:04.478 [main] DEBUG Added 12000000 inferred statements
09:11:05.245 [main] DEBUG Added 13000000 inferred statements
09:11:06.019 [main] DEBUG Added 14000000 inferred statements
09:11:06.812 [main] DEBUG Added 15000000 inferred statements
09:11:07.801 [main] DEBUG Added 16000000 inferred statements
09:11:08.594 [main] DEBUG Added 17000000 inferred statements
09:11:09.388 [main] DEBUG Added 18000000 inferred statements
09:11:10.258 [main] DEBUG Added 19000000 inferred statements
09:11:11.251 [main] DEBUG Added 20000000 inferred statements
09:11:12.174 [main] DEBUG Added 21000000 inferred statements
09:11:13.210 [main] DEBUG Added 22000000 inferred statements
09:11:14.280 [main] DEBUG Added 23000000 inferred statements
09:11:15.226 [main] DEBUG Added 24000000 inferred statements
09:11:16.047 [main] DEBUG Added 25000000 inferred statements
09:11:17.023 [main] DEBUG Added 26000000 inferred statements
09:11:17.855 [main] DEBUG Added 27000000 inferred statements
09:11:18.658 [main] DEBUG Added 28000000 inferred statements
09:11:19.745 [main] DEBUG Added 29000000 inferred statements
09:11:20.582 [main] DEBUG Added 30000000 inferred statements
09:11:21.382 [main] DEBUG Added 31000000 inferred statements
09:11:22.225 [main] DEBUG Added 32000000 inferred statements
09:11:23.099 [main] DEBUG Added 33000000 inferred statements
09:11:24.111 [main] DEBUG Added 34000000 inferred statements
09:11:25.144 [main] DEBUG Added 35000000 inferred statements
09:11:26.129 [main] DEBUG Added 36000000 inferred statements
09:11:27.073 [main] DEBUG Added 37000000 inferred statements
09:11:28.082 [main] DEBUG Added 38000000 inferred statements
09:11:29.041 [main] DEBUG Added 39000000 inferred statements
09:11:29.888 [main] DEBUG Added 40000000 inferred statements
09:11:30.709 [main] DEBUG Added 41000000 inferred statements
09:11:31.690 [main] DEBUG Added 42000000 inferred statements
09:11:32.478 [main] DEBUG Added 43000000 inferred statements
09:11:33.251 [main] DEBUG Added 44000000 inferred statements
09:11:34.160 [main] DEBUG Added 45000000 inferred statements
09:11:35.128 [main] DEBUG Added 46000000 inferred statements
09:11:36.056 [main] DEBUG Added 47000000 inferred statements
09:11:37.076 [main] DEBUG Added 48000000 inferred statements
09:11:38.096 [main] DEBUG Added 49000000 inferred statements
09:11:39.040 [main] DEBUG Added 50000000 inferred statements
09:11:39.988 [main] DEBUG Added 51000000 inferred statements
09:11:40.825 [main] DEBUG Added 52000000 inferred statements
09:11:41.663 [main] DEBUG Added 53000000 inferred statements
09:11:42.563 [main] DEBUG Added 54000000 inferred statements
09:11:43.358 [main] DEBUG Added 55000000 inferred statements
09:11:44.374 [main] DEBUG Added 56000000 inferred statements
09:11:45.153 [main] DEBUG Added 57000000 inferred statements
09:11:46.078 [main] DEBUG Added 58000000 inferred statements
09:11:47.100 [main] DEBUG Added 59000000 inferred statements
09:11:48.045 [main] DEBUG Added 60000000 inferred statements
09:11:49.103 [main] DEBUG Added 61000000 inferred statements
09:11:50.159 [main] DEBUG Added 62000000 inferred statements
09:11:51.114 [main] DEBUG Added 63000000 inferred statements
09:11:52.152 [main] DEBUG Added 64000000 inferred statements
09:11:53.069 [main] DEBUG Added 65000000 inferred statements
09:11:53.991 [main] DEBUG Added 66000000 inferred statements
09:11:55.102 [main] DEBUG Added 67000000 inferred statements
09:11:56.099 [main] DEBUG Added 68000000 inferred statements
09:11:57.024 [main] DEBUG Added 69000000 inferred statements
09:11:58.019 [main] DEBUG Added 70000000 inferred statements
09:11:59.017 [main] DEBUG Added 71000000 inferred statements
09:12:00.002 [main] DEBUG Added 72000000 inferred statements
09:12:01.005 [main] DEBUG Added 73000000 inferred statements
09:12:02.007 [main] DEBUG Added 74000000 inferred statements
09:12:02.479 [main] DEBUG Add inferred rdfs:subPropertyOf statements
09:12:02.481 [main] DEBUG Forward chain all explicit statements
09:12:03.213 [main] DEBUG Added 75000000 inferred statements
09:12:04.461 [main] DEBUG Added 76000000 inferred statements
09:12:05.626 [main] DEBUG Added 77000000 inferred statements
09:12:06.828 [main] DEBUG Added 78000000 inferred statements
09:12:08.062 [main] DEBUG Added 79000000 inferred statements
09:12:09.354 [main] DEBUG Added 80000000 inferred statements
09:12:10.662 [main] DEBUG Added 81000000 inferred statements
09:12:12.003 [main] DEBUG Added 82000000 inferred statements
09:12:12.597 [main] DEBUG Forward chained 1000000 statements
09:12:13.318 [main] DEBUG Added 83000000 inferred statements
09:12:14.641 [main] DEBUG Added 84000000 inferred statements
09:12:15.891 [main] DEBUG Added 85000000 inferred statements
09:12:17.130 [main] DEBUG Added 86000000 inferred statements
09:12:18.385 [main] DEBUG Added 87000000 inferred statements
09:12:19.601 [main] DEBUG Added 88000000 inferred statements
09:12:20.889 [main] DEBUG Added 89000000 inferred statements
09:12:22.212 [main] DEBUG Added 90000000 inferred statements
09:12:22.848 [main] DEBUG Forward chained 2000000 statements
09:12:23.567 [main] DEBUG Added 91000000 inferred statements
09:12:24.927 [main] DEBUG Added 92000000 inferred statements
09:12:26.288 [main] DEBUG Added 93000000 inferred statements
09:12:27.613 [main] DEBUG Added 94000000 inferred statements
09:12:28.813 [main] DEBUG Added 95000000 inferred statements
09:12:30.087 [main] DEBUG Added 96000000 inferred statements
09:12:31.363 [main] DEBUG Added 97000000 inferred statements
09:12:32.665 [main] DEBUG Added 98000000 inferred statements
09:12:33.269 [main] DEBUG Forward chained 3000000 statements
09:12:34.016 [main] DEBUG Added 99000000 inferred statements
09:12:35.100 [main] DEBUG Inferencing complete
09:12:35.101 [main] DEBUG Flush updates
09:12:35.101 [main] DEBUG Flush updates
Query
09:12:35.141 [main] DEBUG Flush updates
[type=http://www.w3.org/2000/01/rdf-schema#Resource]
[type=http://www.wikidata.org/entity/Q14874298]
[type=http://www.wikidata.org/entity/Q42417296]
[type=http://www.wikidata.org/entity/Q28813620]
[type=http://www.wikidata.org/entity/Q18603648]
[type=http://www.wikidata.org/entity/Q3392853]
[type=http://www.wikidata.org/entity/Q64732777]
[type=http://www.wikidata.org/entity/Q7189713]
[type=http://www.wikidata.org/entity/Q483247]
[type=http://www.wikidata.org/entity/Q42183538]
[type=http://www.wikidata.org/entity/Q31836626]
[type=http://www.wikidata.org/entity/Q42982]
[type=http://www.wikidata.org/entity/Q26907166]
[type=http://www.wikidata.org/entity/Q14912053]
[type=http://www.wikidata.org/entity/Q1190554]
[type=http://www.wikidata.org/entity/Q5958765]
[type=http://www.wikidata.org/entity/Q639907]
[type=http://www.wikidata.org/entity/Q14819849]
[type=http://www.wikidata.org/entity/Q20937557]
[type=http://www.wikidata.org/entity/Q32540]
[type=http://www.wikidata.org/entity/Q55919789]
[type=http://www.wikidata.org/entity/Q937228]
[type=http://www.wikidata.org/entity/Q14905642]
[type=http://www.wikidata.org/entity/Q12136]
[type=http://www.wikidata.org/entity/Q18558143]
[type=http://www.wikidata.org/entity/Q193181]
[type=http://www.wikidata.org/entity/Q14904580]
[type=http://www.wikidata.org/entity/Q16887380]
[type=http://www.wikidata.org/entity/Q3631290]
[type=http://www.wikidata.org/entity/Q1150070]
[type=http://www.wikidata.org/entity/Q813912]
[type=http://www.wikidata.org/entity/Q855395]
[type=http://www.wikidata.org/entity/Q14887714]
[type=http://www.wikidata.org/entity/Q14905917]
[type=http://www.wikidata.org/entity/Q22271820]
[type=http://www.wikidata.org/entity/Q35120]
[type=http://www.wikidata.org/entity/Q3286546]
[type=http://www.wikidata.org/entity/Q754447]
[type=http://www.wikidata.org/entity/Q4026292]
[type=http://www.wikidata.org/entity/Q3843811]
[type=http://www.wikidata.org/entity/Q3249551]
[type=http://www.wikidata.org/entity/Q505142]
[type=http://www.wikidata.org/entity/Q101991]
[type=http://www.wikidata.org/entity/Q28807560]
[type=http://www.wikidata.org/entity/Q14916317]
[type=http://www.wikidata.org/entity/Q3505845]
[type=http://www.wikidata.org/entity/Q12192]
[type=http://www.wikidata.org/entity/Q1284347]
[type=http://www.wikidata.org/entity/Q160402]
[type=http://www.wikidata.org/entity/Q22299433]
[type=http://www.wikidata.org/entity/Q1207505]
[type=http://www.wikidata.org/entity/Q14859560]
[type=http://www.wikidata.org/entity/Q22270763]
[type=http://www.wikidata.org/entity/Q18557436]
[type=http://www.wikidata.org/entity/Q29182544]
[type=http://www.wikidata.org/entity/Q14907126]
[type=http://www.wikidata.org/entity/Q14907247]
[type=http://www.wikidata.org/entity/Q25383952]
[type=http://www.wikidata.org/entity/Q99527517]
[type=http://www.wikidata.org/entity/Q12397808]
[type=http://www.wikidata.org/entity/Q22299483]
[type=http://www.wikidata.org/entity/Q169872]
[type=http://www.wikidata.org/entity/Q13878858]
[type=http://www.wikidata.org/entity/Q781413]
[type=http://www.wikidata.org/entity/Q2057971]
[type=http://www.wikidata.org/entity/Q929833]
[type=http://www.wikidata.org/entity/Q2996394]
[type=http://www.wikidata.org/entity/Q1149305]
[type=http://www.wikidata.org/entity/Q21170479]
[type=http://www.wikidata.org/entity/Q16722960]
[type=http://www.wikidata.org/entity/Q14820936]
[type=http://www.wikidata.org/entity/Q58415929]
[type=http://www.wikidata.org/entity/Q1963588]
[type=http://www.wikidata.org/entity/Q14907559]
[type=http://www.wikidata.org/entity/Q18553224]
[type=http://www.wikidata.org/entity/Q1441305]
[type=http://www.wikidata.org/entity/Q18123741]
[type=http://www.wikidata.org/entity/Q1612119]
[type=http://www.wikidata.org/entity/Q14819911]
[type=http://www.wikidata.org/entity/Q32552]
80

Took: 00:03:03.068
```

**Comment by hmottestad** [comment]
TODO:
- [ ] Remove the RDFSChallenge class before merging
- [ ] Run benchmarks (before/after) to verify performance

**Comment by hmottestad** [comment]
### Before
```

Benchmark                                                                                        (param)  Mode  Cnt   Score   Error  Units
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                            moreRdfs::12180  avgt    3  19.329 ± 3.140  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                            longChain::5803  avgt    3  17.389 ± 5.664  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                                medium::544  avgt    3   1.279 ± 0.048  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                                simple::152  avgt    3   0.791 ± 0.025  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions        moreRdfs::12180  avgt    3  13.677 ± 1.032  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions        longChain::5803  avgt    3  16.933 ± 2.610  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions            medium::544  avgt    3   1.127 ± 0.041  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions            simple::152  avgt    3   0.782 ± 0.026  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema  moreRdfs::12180  avgt    3  12.675 ± 0.802  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema  longChain::5803  avgt    3  13.176 ± 0.493  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema      medium::544  avgt    3   0.618 ± 0.041  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema      simple::152  avgt    3   0.292 ± 0.010  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                      moreRdfs::12180  avgt    3  13.574 ± 0.567  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                      longChain::5803  avgt    3  12.763 ± 0.394  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                          medium::544  avgt    3   0.620 ± 0.013  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                          simple::152  avgt    3   0.294 ± 0.008  ms/op
ReasoningBenchmark.noReasoning                                                           moreRdfs::12180  avgt    3   4.173 ± 0.871  ms/op
ReasoningBenchmark.noReasoning                                                           longChain::5803  avgt    3   1.821 ± 0.058  ms/op
ReasoningBenchmark.noReasoning                                                               medium::544  avgt    3   0.291 ± 0.008  ms/op
ReasoningBenchmark.noReasoning                                                               simple::152  avgt    3   0.124 ± 0.015  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                       moreRdfs::12180  avgt    3   4.044 ± 0.383  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                       longChain::5803  avgt    3   1.819 ± 0.376  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                           medium::544  avgt    3   0.292 ± 0.040  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                           simple::152  avgt    3   0.125 ± 0.008  ms/op
```

### After
```

```

**Review by jeenbroekstra — APPROVED** [review]
Looks good. Fwiw if you wanted to make a case to count this as a patch for 4.0.1 (and merge to main) I could live with that.

**Pull request merged**
