### PR TITLE
GH-2799 avoid OOM through HashMap resizing by setting initial size

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #2799 

Briefly describe the changes proposed in this PR:

- initialize the LinkedHashModel with a fixed size equal to the threshold we use for overflow to disk - this should avoid unexpected resizing before overflow is triggered
- note that LinkedHashModel itself internally already uses `size * 2` for the statement set to compensate for the load factor, so using the exact block size should be fine for our purposes

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
There's a bit of a false assumption in this change I just realized, due to poor variable/constant naming: although the `LARGE_BLOCK` constant plays a roll in the overflow trigger, it is not as simple as "overflow when we have more statements than this fixed constant". 

Alternative is that we move the "10% of the heap is still free" requirement up a bit, to, say, 15%?

**Comment by hmottestad** [comment]
I think we should start with a test, or a benchmark if that's easier. Essentially limit the memory available and load in a big file. I'm also curious if this scales as it should, eg. does loading in a bigger file while giving more memory trigger the overflow as consistently as loading a smaller file with less memory available?

**Comment by jeenbroekstra** [comment]
Not at my desk right now, but I believe there's an existing compliance test for the overflow that we could extend if necessary.

**Comment by jeenbroekstra** [comment]
I'm not aware of a simple way to control the available heap space for a single junit test - so we may want to "abuse" a jmh benchmark for this purpose. I'm currently out of spare time, so won't continue on this immediately. @hmottestad if you have an idea and time/will to set up such a test feel free to add it on to this branch.

**Comment by hmottestad** [comment]
After I commented here I set out to google if maybe junit 5 could fork the JVM for a test to configure the amount of memory. Could not find anything. I guess abusing JMH might be the only way unfortunately.

**Comment by jeenbroekstra** [comment]
To be fair even with benchmarking in place there's only so much we can do to make  this work better: at the end of the day we are relying on an _estimate_ of available heap space and predicted usage to trigger disk overflow. In real life situations that estimate could be way off because of circumstances beyond our control (e.g. some different Java object suddenly consuming a lot of memory or something as basic as the data currently being uploaded suddenly containing a few massive literal values). We make a best effort, but we can't _guarantee_ the process won't run out of memory.

**Comment by jeenbroekstra** [comment]
Btw a reason disk syncing on memory overflow is giving us such a performance hit was given by Arjohn Kampman on the mailinglist:

> The reason that syncing the data to disk when the overflow is triggered takes so long is also related to a call to dataset(). When overflowToDisk() calls disk.addAll(memory), this triggers a call to SailSourceModel.add(s,p,o,c...) for each statement. This method then calls both contain(s,p,o,c...) and sink().approve(s,p,o.c) for for each statement. The latter call starts a new transaction and updates the txn-status file, but the contains() call then commits the transaction for the previous statement via a call to dataset(), again updating the txn-status file. So for every cached statement, rdf4j does two I/O calls. On a spinning disk with a an average write time of 10 ms, this limits the overflow process to at most 50 statements per second.

That is not _directly_ related to this fix, but if we can address some of that, we can have more confidence that setting a lower overflow threshold won't cause a massive performance penalty.

**Comment by hmottestad** [comment]
Do you mind @jeenbroekstra if I force push this branch? I would like to add a commit with a benchmark as the first commit in this branch so that we can easily test before and after.

**Comment by jeenbroekstra** [comment]
Go for it

**Comment by hmottestad** [comment]
ok, I've just force pushed, but will need to force push at least one more time before I'm done.

**Comment by hmottestad** [comment]
I've added two benchmarks, one synthetic and one with a real world file.

The synthetic one I've got failing with very low memory. The real world file I've got failing with higher memory. Both are failing at different places. And to make things even more complicated the real world file is failing only within a certain memory range (500-700 MB), outside of that range it either overflows correctly or doesn't need to overflow.

**Comment by hmottestad** [comment]
The synthetic benchmark only fails on java 8 for me.

**Comment by jeenbroekstra** [comment]
Related: #2998

**Comment by hmottestad** [comment]
Not going to dig any further now. I've spent like 3 hours on this because IntelliJ was acting up and running the benchmarks takes a long time.

**Comment by jeenbroekstra** [comment]
I'm becoming more and more convinced that we should invest in replacing the current MemoryOverflowModel with a completely different implementation, something that just relies on standard Java Object Serialization or some simple abstraction like MapDB for disk syncing. I will try and spike something, see what we get.

**Comment by hmottestad** [comment]
Maybe for the time being just try to adjust the point where the model overflows to disk. Perhaps you can add some logging to show what it currently thinks is going on memory wise so you can see what numbers it's comparing. Also maybe try without Xms in the benchmark. 

The real world benchmark is best to start with I think.

**Comment by hmottestad** [comment]
I did some logging and found out that sometimes the algorithm would decide that the max block size was something like 10 MB. This is when it would overflow. So I've just added a hard limit of 32MB of required available memory. This works fine for both my tests (benchmarks) and I feel it's a reasonable tradeoff. How many users give their NativeStore 64MB or 128MB and then load large files?

**Comment by jeenbroekstra** [comment]
> I did some logging and found out that sometimes the algorithm would decide that the max block size was something like 10 MB. This is when it would overflow. So I've just added a hard limit of 32MB of required available memory. This works fine for both my tests (benchmarks) and I feel it's a reasonable tradeoff. How many users give their NativeStore 64MB or 128MB and then load large files?

This seems reasonable to me as well, nice workaround.

**Review by jeenbroekstra — COMMENTED** [review]
LGTM, happy to have this merged. I'll leave it to you.

**Pull request merged**
