### PR TITLE
GH-3720 add Lucene language and type filtering

### PR DESCRIPTION
**Pull request by ate47**
GitHub issue resolved: #3720 

Briefly describe the changes proposed in this PR:

It add parameters in the LuceneSail to filter the indexed element by languages and types.

- ``INDEXEDLANG``: Check when we are indexing a Literal that the language of the literal is one of the elements in the parameters. 
  Example: ``INDEXEDLANG=fr en`` to filter only French and English literals.
- ``INDEXEDTYPES``: Check for the triple (?s my:pred my:type) in the store or update query before adding an element to the store, my:pred and my:type can be configured. 
  Example:``INDEXEDTYPES="http\\://example.org/oftype=http\\://example.org/type1"``, will filter all the subjects ?s without the triple (?s http://example.org/oftype, http://example.org/type1) in the store or the query.

Another parameter ``INDEX_TYPE_BACKTRACE_MODE`` can be set with the method ``setIndexBacktraceMode(TypeBacktraceMode)`` to define how Lucene should handle the add and a remove of a type triple (?s my:pred my:type):

- ``TypeBacktraceMode.COMPLETE``: will check every triples with ?s and try to add or remove them in the Lucene Index
- ``TypeBacktraceMode.PARTIAL``: won't check previous triples in the store, assume that the user would add new elements to the index after and with the add of a type triple and would remove elements to the index with the remove of type.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Review by jeenbroekstra — COMMENTED** [review]
Impressive work @ate47, this looks very good to me!

Do you think you could add something to the documentation (at https://rdf4j.org/documentation/programming/lucene/) about these new config options as well? The markdown file for this is at https://github.com/eclipse/rdf4j/blob/main/site/content/documentation/programming/lucene.md

**Comment by ate47** [comment]
Done, I've also rebased my commits on the develop branch

**Comment by jeenbroekstra** [comment]
Thanks @ate47 ! Looks like the rebase introduce a couple of small compile errors though. Could you take a look?

**Comment by ate47** [comment]
A little oversight from my side, it should be good now.

**Review by jeenbroekstra — APPROVED** [review]

**Pull request merged**
