### PR TITLE
GH-2967 fix nulllpointerexception in SailSourceModel.remove

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #2967  

Briefly describe the changes proposed in this PR:

- added unit test that reproduces the bug
- added additional unit tests on SailSourceModel to have better coverage/compliance
- fixed by making sure private `sink` field is not directly referenced, but only via the `sink()` method

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
Should the sink variable be volatile?

**Comment by jeenbroekstra** [comment]
> Should the sink variable be volatile?

I don't think so, as far as I can tell all access to it is via synchronized methods, so making it volatile won't add anything - unless I missed something. And anyway the issue we're solving here has nothing to do with multithreading.

**Comment by hmottestad** [comment]
You are right. I had to read up more on how synchronized works on the memory model in java and you are correct.

**Comment by ArjohnKampman** [comment]
SailSourceModelTest.testRemoveTermIteration() always fails for me due to a ClosedByInterruptException. Thread's interrupted status prevents the thread from writting the txn-status file.

**Comment by jeenbroekstra** [comment]
> SailSourceModelTest.testRemoveTermIteration() always fails for me due to a ClosedByInterruptException. Thread's interrupted status prevents the thread from writting the txn-status file.

That's peculiar - the test succeeds for me (and on our CI as well). How are you executing it?

**Comment by ArjohnKampman** [comment]
Running from IntelliJ. Will try from command line now.

**Comment by jeenbroekstra** [comment]
@hmottestad could you check this out and run the test in IntelliJ, see if you get the same problem? I'd like to get this merged but if there's something flaky about the test....

**Comment by jeenbroekstra** [comment]
I will merge this fix by the end of the day unless someone has a good reason I shouldn't.

**Comment by ArjohnKampman** [comment]
This change seems to have fixed the NPE that I ran into. I'm still running into out-of-memory-errors, but I guess that's a topic for another ticket.

**Pull request merged**
