### PR TITLE
GH-1371 change of font in web gui

### PR DESCRIPTION
**Pull request by linnaung**
Signed-off-by: Linn Aung <linnyehtutaung@gmail.com>

GitHub issue resolved: # 

Briefly describe the changes proposed in this PR:

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by hmottestad** [comment]
Would this be a good time to move away from using a Microsoft specific font as our default?

**Comment by linnaung** [comment]
if GH-1371 is not in upcoming milestone and not top priority, we could hold this card.

**Comment by jeenbroekstra** [comment]
@linnaung thanks for picking this up. I'm no export on any of this but maybe we could reuse the same font defitions from the rdf4j.org website? 

```
font-family: Roboto,Libre Franklin,Helvetica Neue,Helvetica,Arial,sans-serif
```

Another thing: the font size in the workbench is terrribly small, this has been bugging me for a while. Perhaps this is a good opportunity to fix that, while we're at it. 

I'm fine with doing both fixes on this same card and in this same PR.

**Comment by linnaung** [comment]
@jeenbroekstra, I think reusing from the website is fine for us. but just wanted to clarify since there are several parts to consider. 

Currently the following sections for both (workbench and server) are using:
 
- navigation (left panel)
        -font-size: 83% 
        -font-family: Trebuchet MS, Arial, Helvetica, sans-serif
- content header (top right) 
        -font-size: 83% 
        -font-family: Trebuchet MS, Arial, Helvetica, sans-serif
- footer
        -font-size: 83% 
        -font-family: Trebuchet MS, Arial, Helvetica, sans-serif
- h1, h2, h3, h4
        -font-family: Trebuchet MS, Arial, Helvetica, sans-serif
- html body
        -font family: "Georgia, Times New Roman, Times Roman, Times, serif". 
        -font-size:  100%

Do we intent to change all above sections to "Roboto, Libre Franklin, Helvetica Neue, Helvetica,Arial, sans-serif" as well? 
And which sections that we want to increase font size?

**Comment by jeenbroekstra** [comment]
I'm fine with replacing all of those as a first pass, and setting font size everywhere (except the footer) to 100% (note that for some reason, tables in the content section inherit the font size of 83%). I just tried a quick mockup of that and it looks like this (Firefox on Linux), which I think is acceptable:

Screenshot from 2021-02-02 17-49-01

**Comment by linnaung** [comment]
alright jeen, I will proceed with that.

**Comment by jeenbroekstra** [comment]
Awesome, thanks! By the way if you have any creative ideas on how to improve the frontend beyond these changes, we'd love to hear them. Our webapp's look and feel is severely dated.

**Pull request closed without merging**
