### PR TITLE
GH-3798 Prepare the FunctionCall and And operators.

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #3798 
Briefly describe the changes proposed in this PR:

Start precompiling the binary operators. Taking into account constant propagation.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [X] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by JervenBolleman** [comment]
This is a draft pull request, as I want to do one commit per operator and probably want to move some code out of the very large StrictEvaluationStrategy.

**Comment by hmottestad** [comment]
@JervenBolleman is this PR ready to merge?

**Comment by JervenBolleman** [comment]
I need to double check the merge but otherwise this was ready to go.

**Comment by jeenbroekstra** [comment]
@JervenBolleman this has been sitting for a while now - is all that's needed a rebase before it's ready to merge?

**Comment by JervenBolleman** [comment]
I rebased it and I think it is ready for a merge.

**Comment by abrokenjester** [comment]
@JervenBolleman I'm sorry that we have to keep doing this, but it seems we missed the window to merge this, and it now has several conflicts again. Do you think you have time to try and resolve this? Would be ace if we could get this merged before a 4.3 release...

**Comment by JervenBolleman** [comment]
@abrokenjester no, problem :) I had actually done the work last night. Just had to check that mvn verify had passed this morning.

**Pull request merged**
