### PR TITLE
GH-2843 hashcode for literals needs to include lang tag and datatype

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #2843  

Briefly describe the changes proposed in this PR:

- hash code calculation for literals now includes language tag and datatype
- added regression test

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
@hmottestad I'm getting test failures on the ShaclTest suite and I can't make heads nor tails of it - though it looks to be related to the SHACL engine making some assumptions about language tag equality that aren't quite  correct. Could you have a look?

**Comment by hmottestad** [comment]
Screenshot 2021-02-19 at 06 26 32

It's failing in the last step of the test where it compares the expected and actual validation report. I'll fix it.

**Comment by hmottestad** [comment]
Btw. Does this mean that the new isomorphism algorithm is reliant on the hash so much that it wouldn't detect a collision?

**Comment by jeenbroekstra** [comment]
> Btw. Does this mean that the new isomorphism algorithm is reliant on the hash so much that it wouldn't detect a collision?

I'm not sure what you mean with "detect a collision", but it relies on the hash being globally unique for different values. This is one reasone why we use a 128-bit hash, because collision is for all practical purposes impossible at that size. 

The reason we got problems with literals was that we forgot to include the datatype and language tag in the hash calculation, so two literals with the same lexical value but different datatypes would get the same hashcode.

**Comment by hmottestad** [comment]
> > Btw. Does this mean that the new isomorphism algorithm is reliant on the hash so much that it wouldn't detect a collision?
> 
> I'm not sure what you mean with "detect a collision", but it relies on the hash being globally unique for different values. This is one reason why we use a 128-bit hash, because collision is for all practical purposes impossible at that size.

That's what I meant. That if there were a collision where two different values hashed to the same hash we would not be able to detect that this happened. As you say though, astronomically unlikely. 

Btw. This is what Oracle does for their triple store. Every IRI, blank node and literal is hashed to a 128 bit (or possibly higher) value that is stored on disk. That way you can have constant size blocks on disk combined with a one way dictionary. We instead have a two way dictionary, since we use an incrementing ID instead. So when we have a value and what to know if it's in the database we have to look it up in the reverse dictionary to get the ID, while Oracle just has to hash it. This also leads to an optimization we could do in our codebase. Virtual IRI/BNode/Literal where the actual value isn't retrieved from disk until you need to do more complex operations. Instead for simple things like joins it would just use the ID, and since a lot of data is discarded during typical joins then for that data we wouldn't need to retrieve the actual values from the dictionary.

**Review by hmottestad — APPROVED** [review]
lgtm 👍

**Comment by jeenbroekstra** [comment]
> Btw. This is what Oracle does for their triple store. Every IRI, blank node and literal is hashed to a 128 bit (or possibly wider) hash that is stored on disk. That way you can have constant size blocks on disk (for the index) combined with a one way dictionary. We instead have a two way dictionary, since we use an incrementing ID instead. So when we have a value and what to know if it's in the database we have to look it up in the reverse dictionary to get the ID, while Oracle just has to hash it. This also leads to an optimization we could do in our codebase. Virtual IRI/BNode/Literal where the actual value isn't retrieved from disk until you need to do more complex operations. Instead for simple things like joins it would just use the ID, and since a lot of data is discarded during typical joins then for that data we wouldn't need to retrieve the actual values from the dictionary.

It's an interesting idea - we instead went with marker blocks in the native store, probably because (and don't hold me to this it's a long time ago) at the time disk space was at a premium so we were looking for compactness and making optimal use of java nio page sizing. 

Unfortunately none of us really have the time and resources to implement a new triplestore from scratch (or even to fundamentally refactor the native store). If we did, this would be an interesting approach I think.

**Pull request merged**
