### PR TITLE
GH-3671 isomorphism bug

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #3671 

Briefly describe the changes proposed in this PR:

- added regression test that demonstrates problem
- increasing sha length to 256 bits fixes the issue

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
I'm speculating that the problem has to do with how we combine multiple hashes to calculate unique values, and that there can happen a collission more frequently than anticipated when using a lower size for the hashes.

I've ran a few benchmarks to see if going to a stronger hash would mean a significant performance decrease: 

Using murmur3_128:

```
Benchmark                                          Mode  Cnt  Score   Error  Units
IsomorphicBenchmark.shacl                          avgt   10  3.408 ± 0.212  ms/op
IsomorphicBenchmark.shaclValidationReport          avgt   10  9.749 ± 0.387  ms/op
IsomorphicBenchmark.shaclValidationReport_changed  avgt   10  9.994 ± 0.514  ms/op
```

Using sha256:

```
Benchmark                                          Mode  Cnt   Score   Error  Units
IsomorphicBenchmark.shacl                          avgt   10   3.718 ± 0.168  ms/op
IsomorphicBenchmark.shaclValidationReport          avgt   10  10.669 ± 0.091  ms/op
IsomorphicBenchmark.shaclValidationReport_changed  avgt   10  10.717 ± 0.324  ms/op
```

It is (naturally) slightly slower, but not significantly so.

**Comment by hmottestad** [comment]
Is there no way to detect collisions and maybe resolve them or fail over to the legacy isomorphic algorithm?

**Comment by jeenbroekstra** [comment]
> Is there no way to detect collisions and maybe resolve them or fail over to the legacy isomorphic algorithm?

No.

**Comment by hmottestad** [comment]
> > Is there no way to detect collisions and maybe resolve them or fail over to the legacy isomorphic algorithm?
> 
> No. Or rather: perhaps there is, but it would need significant investment of research and dev time, which I currently don't have. In the mean time, we need to put reliability over performance and merge this as a short term fix.

Just wondering if maybe there is some underlying issue that is causing collisions to be more frequent?

**Comment by jeenbroekstra** [comment]
> > > Is there no way to detect collisions and maybe resolve them or fail over to the legacy isomorphic algorithm?
> > 
> > 
> > No. Or rather: perhaps there is, but it would need significant investment of research and dev time, which I currently don't have. In the mean time, we need to put reliability over performance and merge this as a short term fix.
> 
> Just wondering if maybe there is some underlying issue that is causing collisions to be more frequent?

Oh, yes, most likely. I suspect that it has to do with how we calculate combined hashes. I _think_ we're following the letter of the algorithm as outlined in the technical paper there, but perhaps I've missed something. Certainly, in theory 128 bits should be enough to not cause collisions in graphs of this size (or any practical size, really). Yet clearly we do get a collision of sorts, and clearly using a larger hash size mitigates the issue. Perhaps there's an overflow in the hash combination algorithm that makes it collapse to a smaller value space? The trouble is that I can't quite put my finger on it, and I've not been able to reduce the example - as soon as I take even a few triples out the isomorphism consistently succeeds.

**Comment by hmottestad** [comment]
You're good to merge this as is. 

Could you file a follow up issue though to look into the collisions? Maybe something along the lines of hashing with both murmur and sha to try to find out exactly where the collision is occurring.

**Review by hmottestad — APPROVED** [review]

**Comment by jeenbroekstra** [comment]
> You're good to merge this as is.
> 
> Could you file a follow up issue though to look into the collisions? Maybe something along the lines of hashing with both murmur and sha to try to find out exactly where the collision is occurring.

Yep good point, will do.

**Pull request merged**
