### PR TITLE
#749 added forceSync to AllocatedNodesList

### PR DESCRIPTION
**Pull request by mfarre**
This PR addresses GitHub issue: #749 .

Briefly describe the changes proposed in this PR:

* Added forceSync to AllocatedNodesList

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
@mfarre Thanks for picking this up. Unfortunately, we can't accept your contribution without you having signed the Eclipse Contributor Agreement. Please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the points on how to sign the ECA. Let me know if you need any help with any of it.

**Comment by jeenbroekstra** [comment]
@jamesrdf I'm a little out of touch with the current status, but should this PR be on the rdf4j repo, or against the new rdf4j-store repo instead?

**Comment by mfarre** [comment]
Hello @jeenbroekstra I have just signed the contributor guidelines

**Comment by jamesrdf** [comment]
To target 2.3 this PR needs to be created in [/eclipse/rdf4j-storage/pulls](/eclipse/rdf4j-storage/pulls) and target the develop branch, we are migrating store/eval code to a new project and are still in the middle of updating the docs.

**Comment by mfarre** [comment]
Hello @jamesrdf just added the PR over there https://github.com/eclipse/rdf4j-storage/pull/9 

Thanks,
Miquel

**Pull request closed without merging**
