### PR TITLE
GH-3987 introduce InternedIRI for use in Vocabularies to improve performance

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3987 

Briefly describe the changes proposed in this PR:

 - New (internalOnly) class InternedIRI which interns the stringValue and pre-calculates the hashCode
 - Use InternedIRI in Vocabularies and in CoreDatatype

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
I've changed both https://github.com/eclipse/rdf4j/pull/3990 and this PR to draft for the time being. They both definitely improve performance, but that was only really obvious when combined with #3933.

**Comment by JervenBolleman** [comment]
Hi just a quick thought. Will this really help at scale? I have had bad experiences with intern on string similar to https://shipilev.net/jvm/anatomy-quarks/10-string-intern/

**Comment by hmottestad** [comment]
## Before

```
```

## After
```
Benchmark                                                                                        (param)  Mode  Cnt   Score   Error  Units
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                            moreRdfs::12180  avgt    3  11.611 ± 6.192  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                            longChain::5803  avgt    3   8.134 ± 0.454  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                                medium::544  avgt    3   0.882 ± 0.279  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                                simple::152  avgt    3   0.465 ± 0.091  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions        moreRdfs::12180  avgt    3   8.428 ± 1.013  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions        longChain::5803  avgt    3   8.121 ± 0.168  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions            medium::544  avgt    3   0.759 ± 0.233  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions            simple::152  avgt    3   0.461 ± 0.074  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema  moreRdfs::12180  avgt    3   8.738 ± 0.843  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema  longChain::5803  avgt    3   6.137 ± 0.426  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema      medium::544  avgt    3   0.514 ± 0.056  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema      simple::152  avgt    3   0.222 ± 0.033  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                      moreRdfs::12180  avgt    3   9.325 ± 3.046  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                      longChain::5803  avgt    3   6.213 ± 0.502  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                          medium::544  avgt    3   0.503 ± 0.001  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                          simple::152  avgt    3   0.220 ± 0.007  ms/op
ReasoningBenchmark.noReasoning                                                           moreRdfs::12180  avgt    3   3.979 ± 0.485  ms/op
ReasoningBenchmark.noReasoning                                                           longChain::5803  avgt    3   1.843 ± 0.124  ms/op
ReasoningBenchmark.noReasoning                                                               medium::544  avgt    3   0.297 ± 0.036  ms/op
ReasoningBenchmark.noReasoning                                                               simple::152  avgt    3   0.123 ± 0.005  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                       moreRdfs::12180  avgt    3   3.841 ± 0.864  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                       longChain::5803  avgt    3   1.838 ± 0.409  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                           medium::544  avgt    3   0.294 ± 0.036  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                           simple::152  avgt    3   0.124 ± 0.004  ms/op
```

**Comment by hmottestad** [comment]
## Before
```
Benchmark                                                                                        (param)  Mode  Cnt   Score   Error  Units
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer                            moreRdfs::12180  avgt    5  12.385 ± 0.043  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactions        moreRdfs::12180  avgt    5   9.372 ± 0.072  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerMultipleTransactionsSchema  moreRdfs::12180  avgt    5   9.447 ± 0.019  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencerSchema                      moreRdfs::12180  avgt    5   9.726 ± 0.029  ms/op
ReasoningBenchmark.noReasoning                                                           moreRdfs::12180  avgt    5   3.877 ± 0.016  ms/op
ReasoningBenchmark.noReasoningMultipleTransactions                                       moreRdfs::12180  avgt    5   3.858 ± 0.036  ms/op
```

## After
```
```

**Comment by hmottestad** [comment]
>

**Comment by hmottestad** [comment]
This is showing a decent 10% performance improvement in the more complex RDFS reasoning benchmark.

**Pull request merged**
