### PR TITLE
Gh 3532 checkkout v2 main status

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #3532 

Briefly describe the changes proposed in this PR:

bump checkout action version

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
We don't seem to have an issue GH-3532.

**Comment by JervenBolleman** [comment]
@jeenbroekstra this is just bizare, it was not my issue but one created by some other person basically about the same issue as #3533 just a different action.

**Review by jeenbroekstra — APPROVED** [review]
LGTM - I guess we'll need another PR for the develop status workflow?

**Review by jeenbroekstra — CHANGES_REQUESTED** [review]
Actually just had a look: given that this is for the main branch, shouldn't it be aimed at merging back into main?

**Comment by jeenbroekstra** [comment]
Taken care of in other PR

**Pull request closed without merging**
