### PR TITLE
#1074 Added vocabulary class for the VANN vocab.

### PR DESCRIPTION
**Pull request by pmcb55**
Signed-off-by: Pat McBennett <pat.mcbennett@mastercard.com>

This PR addresses GitHub issue: #1074  .

* Simply added a new vocabulary class for VANN (http://vocab.org/vann/).

### CODE REVIEW

**Comment by barthanssens** [comment]
Excellent, thanks

**Comment by pmcb55** [comment]
Hi Bart - so I've made those changes (I had just used the RDFS.java file as my example, and it has the term 'CONTAINERMEMBERSHIPPROPERTY', which was why I didn't use underscores). I agree that they read much better.

Also, my first commit failed the CI build due to a ip-validation failure, which was due to me forgetting to use my personal email instead of my work one. Anyway, I've pushed the changes again, so is there anything else I need to do now? How does the CI process get kicked off again??

**Comment by barthanssens** [comment]
CI runs after the commit, so that's OK, it can sometimes take a while though

If it fails again due to IP validation (Eclipse foundation is pretty strict about it, sorry, I had the same problem a few occasions), there are two options (that I know of) to fix this:

- somewhat "dirty" approach, rewrite the git history in your branch, there is a script that does exactly that (https://help.github.com/articles/changing-author-info/)
- or, some extra work, close this PR, create a new branch and submit the code again using the correct mail address and create a new PR

**Comment by pmcb55** [comment]
Hi Bart, so I tried that Git rewrite script, but I don't think it worked - can you check? 

If needed I can close this PR and start again (I don't mind too much, as my change is super easy, and all this process is an education for me!).

**Comment by barthanssens** [comment]
Hmz, better to create a new PR and start over again, the script did not only change the owner of your own file, but all other files of the RDF4J source as well :-(

**Comment by barthanssens** [comment]
This PR can be closed, corrected in https://github.com/eclipse/rdf4j/pull/1076

**Pull request closed without merging**
