### PR TITLE
GH-4656 Ugly fix for intermediate join variables breaking down stream assumptions

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #GH-4656

Briefly describe the changes proposed in this PR:

The PathIteration code adds some binding names that it uses internally. These bindings should be removed before passing them on, or other code might break.

This is a very ugly hack but should resolve the problem. I will think about something cleaner.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by vallerap** [comment]
Hello @JervenBolleman 

I have noticed that in your recent commit you referenced Issue [GH-4656](https://github.com/eclipse/rdf4j/pull/4656) as the problem being addressed. However, after reviewing the commit and the issue description, it seems that the referenced issue might have been accidentally mentioned. 

If I understand correctly, this should fix issue [4646](https://github.com/eclipse/rdf4j/issues/4646)?

**Comment by txpn** [comment]
@JervenBolleman , with this fix, I get the same error with a bit more detail in the error message:

`java.lang.AssertionError: We don't actually support adding a binding. asil : "QM"
        at org.eclipse.rdf4j.query.algebra.evaluation.ArrayBindingSet.addBinding(ArrayBindingSet.java:336)
        at org.eclipse.rdf4j.query.MutableBindingSet.addBinding(MutableBindingSet.java:30)
        at org.eclipse.rdf4j.query.algebra.evaluation.impl.evaluationsteps.BindingSetAssignmentQueryEvaluationStep$1.getNextElement(BindingSetAssignmentQueryEvaluationStep.java:67)
        at org.eclipse.rdf4j.query.algebra.evaluation.impl.evaluationsteps.BindingSetAssignmentQueryEvaluationStep$1.getNextElement(BindingSetAssignmentQueryEvaluationStep.java:47)
        at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:80)
...`

**Comment by vallerap** [comment]
> @JervenBolleman , with this fix, I get the same error with a bit more detail in the error message:
> 
> `java.lang.AssertionError: We don't actually support adding a binding. asil : "QM" at org.eclipse.rdf4j.query.algebra.evaluation.ArrayBindingSet.addBinding(ArrayBindingSet.java:336) at org.eclipse.rdf4j.query.MutableBindingSet.addBinding(MutableBindingSet.java:30) at org.eclipse.rdf4j.query.algebra.evaluation.impl.evaluationsteps.BindingSetAssignmentQueryEvaluationStep$1.getNextElement(BindingSetAssignmentQueryEvaluationStep.java:67) at org.eclipse.rdf4j.query.algebra.evaluation.impl.evaluationsteps.BindingSetAssignmentQueryEvaluationStep$1.getNextElement(BindingSetAssignmentQueryEvaluationStep.java:47) at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:80) ...`

I am getting the same error, can we maybe consider reverting [this element in getNextElement](https://github.com/eclipse/rdf4j/blob/b11b4a5061a9313d7a777edca3a9c471a15508e8/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java#L161) to [how it was in 3.7.7](https://github.com/eclipse/rdf4j/blob/b11b4a5061a9313d7a777edca3a9c471a15508e8/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java#L161) ?

**Comment by JervenBolleman** [comment]
Sorry but I am on vacation and I couldn't properly fix it before heading
out without laptop.

Reverting the next element method just leaves the problem in place for
later in the evaluation.

The issue is unexpected variables being added to the query evaluation. This
should be fixed consistently or it could pop up in the future again
elsewhere.

**Comment by JervenBolleman** [comment]
@vallerap is this from the same query? because it mentions a binding asil, but I don't see any such variable in the example query.

**Pull request closed without merging**
