### PR TITLE
GH-3871: Add revealing test case and fix one-off error

### PR DESCRIPTION
**Pull request by maxstolze**
GitHub issue resolved: #3871

Briefly describe the changes proposed in this PR:

* adds a test case in `core/sail/shacl/src/test/resources/test-cases/complex/mms/` that reveals the bug
* fixes the one-off error in `ValidationQuery`, the test still fails with another error - hence draft PR. 
* Help is welcome!
----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by maxstolze** [comment]
After solving the `ArrayIndexOutOfBoundsException` issue, the code currently fails in `ValidationQuery.union()`, where the two ValidationQueries are checked in a number of assert statements. To see which queries are joined, we print them to stdout, here's the output:
```
union of a: 
?target_0000000000 a <https://mms.researchstudio.at/mms#EnumerationType> .
?target_0000000000 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .

FILTER(NOT EXISTS{?value <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .})
union of b: 
?target_0000000000 a <https://mms.researchstudio.at/mms#EnumerationType> .
?target_0000000000 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
?value_0 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
?value_1 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
FILTER(?value_0 != ?value_1)

union of a: 
{
?target_0000000000 a <https://mms.researchstudio.at/mms#EnumerationType> .
?target_0000000000 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .

FILTER(NOT EXISTS{?value <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .})
} UNION {
?target_0000000000 a <https://mms.researchstudio.at/mms#EnumerationType> .
?target_0000000000 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
?value_0 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
?value_1 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
FILTER(?value_0 != ?value_1)

}
union of b: 
?target_0000000000 a <https://mms.researchstudio.at/mms#EnumerationType> .
?target_0000000000 <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
?value <http://www.linkedmodel.org/schema/dtype#hasMember> ?target_0000000001 .
 FILTER(!(EXISTS{?value a <https://mms.researchstudio.at/mms#EnumerationType>}))
2022-05-10 17:24:47,556 [ForkJoinPool-1-worker-5] DEBUG org.eclipse.rdf4j.sail.shacl.ShaclSailConnection - Cleanup

java.lang.AssertionError
	at org.eclipse.rdf4j.sail.shacl.ast.ValidationQuery.union(ValidationQuery.java:84)
	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  [...]
```

The problem seems caused by one of the value variables being called `value` whereas the other is `value_1`

@hmottestad I think we need your help here

**Comment by maxstolze** [comment]
Can't find the cause by our own and will wait now for @hmottestad or someone else who knows, why this happens here.

**Comment by hmottestad** [comment]
I've found the issue and I've tested a fix. Thanks for creating a test case. 

I would like to use your test case in my code, so if you could take a look at the contributor guide and make sure you have signed the Eclipse Contributor Agreement. That way I can merge your branch in with my fix. 

https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#legal-stuff

In short the issue is that some property shape constraints produce values and others don't. Min/max count don't, but class does. So it's correct that the index for the value is out of bounds. The problem here is that the use of sh:node stops the ShaclSail from splitting the shape into multiple shapes and then runs into the bug where the union code doesn't correctly check if the constraint produces a value or not.

**Comment by hmottestad** [comment]
And as a temporary fix you can disable SPARQL based validation, and revert to using the regular bulk or transactional validation for everything. This will make some validations slower. 

You can set the property `org.eclipse.rdf4j.sail.shacl.sparqlValidation` to the `false`. Both as strings. See https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/System.html#setProperty(java.lang.String,java.lang.String)

**Comment by hmottestad** [comment]
I've posted a PR here: https://github.com/eclipse/rdf4j/pull/3877

**Comment by maxstolze** [comment]
Okay, thank you! I've signed the Eclipse Contributor Agreement and you can merge the test case as well.

**Comment by hmottestad** [comment]
Merged into [GH-3871-shacl-index-out-of-bounds](https://github.com/eclipse/rdf4j/tree/GH-3871-shacl-index-out-of-bounds)

**Pull request closed without merging**
