### PR TITLE
GH-3535 pr-verify uses checkout v2

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #3533 

Briefly describe the changes proposed in this PR:
bump checkout action to v2

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@hmottestad I have strange failure in one of the ShACL tests? could it be similar to the recent one I found with synchronisation issues?

**Comment by hmottestad** [comment]
Those tests are "isolated" so they don't run in parallel with other tests.

**Comment by hmottestad** [comment]
Log file from the failure.

[log.txt](https://github.com/eclipse/rdf4j/files/7764325/log.txt)

**Comment by jeenbroekstra** [comment]
@JervenBolleman is something going wrong with your fork, or something? I assume you didn't just make the ticket numbers up but both on this PR and on the other one related tothe checkout action the issue ticket number doesn't exist (I get a 404 when I click on it).

**Comment by JervenBolleman** [comment]
@jeenbroekstra  I am really confused. #3533 exists right now. #3532 is indeed gone?

**Comment by jeenbroekstra** [comment]
@JervenBolleman Very odd... I think what may have happened is that github detected/suspected that those issues were created by some automated agent and marked them as spam somehow?

**Review by jeenbroekstra — APPROVED** [review]
I'm ok with merging this.

**Pull request merged**
