### PR TITLE
GH-4146 Fixes for REST Isolation-level settings

### PR DESCRIPTION
**Pull request by nguyenm100**
patch for: https://github.com/eclipse/rdf4j/issues/4146

resubmitting with correct credentials to satisfy eca

### CODE REVIEW

**Comment by nguyenm100** [comment]
@jeenbroekstra - please use this PR for the Isolation fixes.  It has your feedback updates..  I accidentally checked in some of my changes using my work email on the last PR and it failed the eca.

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra - please use this PR for the Isolation fixes. It has your feedback updates.. I accidentally checked in some of my changes using my work email on the last PR and it failed the eca.

Thanks for taking care of it! I've done that a few times myself. Btw you may know this already but you can set the e-mail address used for your commits on a specific repo by navigating to the repo root and doing `git config user.email <email>`. You can also set a global (on your current machine) default by doing `git config --global user.email <email>`.

**Comment by jeenbroekstra** [comment]
@nguyenm100 as an aside, could you take another glance at our [contribution guidelines](https://github.com/eclipse/rdf4j#keen-to-contribute), in particular the points about commit messages, PR descriptions and such? For one thing, we make a point of having the Github issue number at the start of every commit message and at the start of the PR title as well. This makes it easier for us to relate changes back to the issue even after things have been merged.

No worries if occasionally something slips through of course, but I'd prefer it not to become a habit :)

**Review by jeenbroekstra — APPROVED** [review]
Nice work!

**Pull request merged**
