### PR TITLE
GH-3410 improve MemStatementsIterator

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3410 

Briefly describe the changes proposed in this PR:

 - optimised the filtering in MemStatementsIterator to prioritise non-volatile variables over volatile ones
     - this is what makes the biggest difference
 - optimise the access to variables needed during filtering
 - cleaned up some code while I was at it
 - updated benchmarks
 - removed a bunch of volatile use in various iterators and in the memory store in general
      - this is kinda unrelated to the general work and I should really make some multithreaded benchmarks to measure these changes

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
```
Benchmark                            (isolationLevel)  Mode     Score (before)     Score (after)
QueryBenchmark.complexQuery                      NONE  avgt        162.599             85.341
QueryBenchmark.complexQuery            READ_COMMITTED  avgt        163.002             85.166
QueryBenchmark.groupByQuery                      NONE  avgt          3.375              3.003
QueryBenchmark.groupByQuery            READ_COMMITTED  avgt          3.480              3.085
QueryBenchmark.orderbyQuery9                     NONE  avgt        866.288            909.215
QueryBenchmark.orderbyQuery9           READ_COMMITTED  avgt        814.576            833.064
QueryBenchmark.pathExpressionQuery1              NONE  avgt         27.158             24.285
QueryBenchmark.pathExpressionQuery1    READ_COMMITTED  avgt         26.986             24.863
QueryBenchmark.pathExpressionQuery2              NONE  avgt          3.386              3.217
QueryBenchmark.pathExpressionQuery2    READ_COMMITTED  avgt          3.387              3.245
QueryBenchmark.removeByQuery                     NONE  avgt          9.859              8.938
QueryBenchmark.removeByQuery           READ_COMMITTED  avgt         17.674             15.309
QueryBenchmark.simpleUpdateQuery                 NONE  avgt         53.843             47.863
QueryBenchmark.simpleUpdateQuery       READ_COMMITTED  avgt         70.703             70.038
```

**Comment by hmottestad** [comment]
Might revert the isolation level modifications to the benchmark since it's making such a small difference for read based operations.

**Comment by hmottestad** [comment]
Screenshot 2021-11-12 at 18 41 11

**Comment by hmottestad** [comment]
I still need to clean up the commits, but I've left them like this for now in case I need to remove something.

Benchmark runs in the screenshot above show that the biggest change is for the complex query benchmark, which now takes ~50% as much time as before. This is the same as saying that it's ~2x faster.

**Review by barthanssens — APPROVED** [review]
LGTM, nice to see that a few variables don't need to be volatile (anymore)

**Review by jeenbroekstra — APPROVED** [review]
Looks good, nice cleanup, great to see we can get rid of so much unnecessary concurrency control bloat too. Looks good to be merged for me as soon as the commit history is tidied up :+1:

**Pull request merged**
