### PR TITLE
Gh 4043 fix missing copyright headers

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #4043 
Briefly describe the changes proposed in this PR:
Add missing copyright headers and hopefully a github workflow that checks for this in the future.

----
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
Looks good! Maybe we want this on the main branch too?

**Comment by JervenBolleman** [comment]
@hmottestad sure. Once we are confident it works lets add the script as a check on the main branch.

**Comment by jeenbroekstra** [comment]
> @hmottestad sure. Once we are confident it works lets add the script as a check on the main branch. For now ok for me to merge?

I'm fine with merging this, but just wanted to point out that this makes it a bit harder for yourself. If you add this in main first (which is fine for these kinds of internal tasks), it automatically also gets added to develop when the branches sync, but if you merge to develop first, you'll have to cherrypick it to get it into main also (and in some cases you may have to deal with merge conflicts later on when main and develop sync).

**Review by jeenbroekstra — APPROVED** [review]

**Comment by JervenBolleman** [comment]
@jeenbroekstra and @hmottestad I will rebase this against master then.

**Pull request merged**
