### PR TITLE
Overhaul of project Java EE dependencies

### PR DESCRIPTION
**Pull request by erikgb**
This PR is a draft for an overhaul of the Java EE dependencies in the project. To support/verify this, I also added a few maven-enforcer-plugin executions - to highlight which modules that may require special attention when trying to upgrade Java/Jakarta EE.

### CODE REVIEW

**Comment by erikgb** [comment]
@abrokenjester Does this draft PR make sense to you? I am open to dropping the maven-enforcer-plugin configuration, as it became a bit complex. But it verifies/checks the main goal in this PR: overhaul/reduce the Java/Jakarta EE dependencies.

**Comment by abrokenjester** [comment]
@erikgb sorry for not responding sooner - this PR somehow wasn't on my "to review" radar. 

It's problematic for me to really review this as well, as my knowledge of (current) Java EE and Jakarta is really limited. In short, I'm simply not really sure what this is trying to achieve. Could you perhaps add some review comments inline yourself to explain what this is doing and why?

**Comment by erikgb** [comment]
@abrokenjester Sorry for being slow on the iterations, but I have been busy with other things lately. I'll probably pull out some cleanup of unused J2EE dependencies from this PR to a new issue + PR and close this PR. The suggested enforcer configuration will probably create more confusion than good. I think reducing J2EE/Jakarta dependencies will improve the codebase, at least the stated, but unneeded dependencies.

**Comment by erikgb** [comment]
Seems like the unused J2EE dependencies are already removed. Closing.

**Pull request closed without merging**
