### PR TITLE
#1031 allow flushing for SERIALIZABLE transactions

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #1031  

Briefly describe the changes proposed in this PR:

* 
* 
*

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra @barthanssens this is my proposed fix to the SERIALIZALE memory issue, hopefully it's old code that we don't need anymore....

**Comment by barthanssens** [comment]
LGTM, there is good karma in solving old bugs with only a few keystrokes :-)

**Comment by hmottestad** [comment]
I have no tests for this. Would appreciate if someone could figure out a decent one.

**Comment by barthanssens** [comment]
Would this be a thing for the benchmarks, but perhaps for all stores and isolation levels ?
The java file attached to #1031 was already very helpful, so maybe adapt that one and just test if memory does not increase too much ?

**Comment by jeenbroekstra** [comment]
Fwiw I ran the attached java scratch with this fix in place, and am getting much better results:

```
 1       6,236
 2      10,596
 3       9,403
 4       8,536
 5      10,425
 6       7,710
 7       7,136
 8       8,550
 9       8,067
10       9,837
11       6,766
12       7,042
13       7,158
14       7,287
15       6,700
finished in 22 s.
```

**Comment by jeenbroekstra** [comment]
Fwiw I am taking a closer look at the compliance tests we have for txn isolation. I've noticed that most of the tests we have work with very small transactions - I'll do a probe to see if we can make those tests work with slightly larger batches.

**Pull request merged**
