### PR TITLE
GH-2211 more thread safe upgrading of the DynamicModel

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #221 

Briefly describe the changes proposed in this PR:

 - LinkedHashMap is not removed while upgrading, allowing current users to keep using it
 - Upgrading during a write will now wait for the write to complete, thanks to synchronized writes
 
---- 
PR Author Checklist: 

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by hmottestad** [comment]
I don't have a test for this, the bug was reproduced in a ShaclSail test. It doesn't seem that we have any decent multi-threaded reader with single writer tests for model, even though we use them in that way in the code. I know that the TreeModel has a race condition for this, and now apparently so the does the LinkedHashModel.

**Comment by jeenbroekstra** [comment]
The Model classes, like most Java Collection classes, are not thread-safe by design. I haven't looked in detail at the problem yet but if there are places in the code where we assume a Model class is thread-safe, surely the fix is to change that assumption and make sure the code accesses the model in a thread-safe manner, rather than try and make all model implementations themselves thread-safe.

**Comment by hmottestad** [comment]
From ArrayList docs (for reference): 

> Note that this implementation is not synchronized. If multiple threads access an ArrayList instance concurrently, and at least one of the threads modifies the list structurally, it must be synchronized externally.

Current implementation of the DynamicModel isn’t thread safe for multiple readers if one of the readers forces the model to upgrade. This is fixed in the pr. 

If the cost of synchronizing writes is small I think it’s a worthwhile fix to remove the chance that we write to the wrong underlying storage during multithreaded reads and single-threaded writes.

**Comment by hmottestad** [comment]
I’ve now removed the synchronization again. I think you are right that we don’t want to imply thread safety. Multiple reader thread safety is nice to have though, so that is fixed in this PR, and I also have test to check for best-effort detection of concurrent access.

**Comment by hmottestad** [comment]
TODO: Edit the java docs

**Comment by hmottestad** [comment]
I believe this is done now and ready for review.

**Pull request merged**
