### PR TITLE
GH-3978 rerun javacc and apply optimizations and cleanup

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3978 

Briefly describe the changes proposed in this PR:

Rerun javacc and apply optimizations and cleanup.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
## Before
```
```

## After
```

```

**Comment by hmottestad** [comment]
## Commands I used to run JavaCC

```
gh repo clone javacc/javacc 
cd javacc
ant
mkdir output
cd output     
# Now I copied the sparql.jjt file into the output directory.
chmod +x ../scripts/jjtree
chmod +x ../scripts/javacc
../scripts/jjtree sparql.jjt
../scripts/javacc sparql.jj
```

I didn't copy over any of the AST* files because most of these were not generated correctly. I don't know why. Maybe we have updated them manually?

**Comment by hmottestad** [comment]
This fixes a regression where the LookAheadException was triggering a stack trace every time the parser was instantiated. It was fixed a few years ago in JavaCC.

**Comment by hmottestad** [comment]
I think that this branch is a good place to add some documentation and reproducibility for JavaCC. 

One major issue that I had was that the SimpleNode class was missing a bunch of methods, and that quite a few of the AST* classes were inheriting from the wrong super class and some were also missing some functionality. 

Our old SimpleNode used an ArrayList, which might be more efficient than the plain array that the generated SimpleNode uses. I don't know if this is something that we modified ourselves or if it's a change in JavaCC. I haven't put any effort into figuring it out either. 

When generating the java code there were also a couple of AST* classes that were not generated by JavaCC. That makes me wonder if maybe they were added manually instead. 

I also think that I should try to contribute some of the performance optimizations back to JavaCC, that way we don't need so many git patch files.

**Comment by jeenbroekstra** [comment]
Sounds good. Sorry I haven't found time yet to look at this further. Will try and do so  ASAP.

**Pull request merged**
