### PR TITLE
Gh 2809 faster hashcode collection equals

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: # 

Briefly describe the changes proposed in this PR:

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by hmottestad** [comment]
After
```
Benchmark                                          Mode  Cnt     Score   Error  Units
IsomorphicBenchmark.blankNodes                     avgt    2     4.998          ms/op
IsomorphicBenchmark.blankNodesLarge                avgt    2  6964.143          ms/op
IsomorphicBenchmark.bsbm                           avgt    2    43.681          ms/op
IsomorphicBenchmark.bsbmArrayList                  avgt    2   141.421          ms/op
IsomorphicBenchmark.bsbmNotIsomorphic              avgt    2    26.989          ms/op
IsomorphicBenchmark.bsbmTree                       avgt    2    71.214          ms/op
IsomorphicBenchmark.empty                          avgt    2    ≈ 10⁻⁴          ms/op
IsomorphicBenchmark.emptyNotIsomorphic             avgt    2    ≈ 10⁻⁵          ms/op
IsomorphicBenchmark.internallyIsomorphic           avgt    2   330.034          ms/op
IsomorphicBenchmark.list                           avgt    2     7.533          ms/op
IsomorphicBenchmark.listEquals                     avgt    2     1.051          ms/op
IsomorphicBenchmark.longChain                      avgt    2     0.016          ms/op
IsomorphicBenchmark.manyProperties                 avgt    2    10.078          ms/op
IsomorphicBenchmark.manyProperties2                avgt    2     7.314          ms/op
IsomorphicBenchmark.sameModel                      avgt    2    ≈ 10⁻⁶          ms/op
IsomorphicBenchmark.shacl                          avgt    2     3.068          ms/op
IsomorphicBenchmark.shaclValidationReport          avgt    2     9.506          ms/op
IsomorphicBenchmark.shaclValidationReport_changed  avgt    2     8.876          ms/op
IsomorphicBenchmark.sparqlTestCase                 avgt    2     0.051          ms/op
IsomorphicBenchmark.spinFullForwardchained         avgt    2    48.916          ms/op
IsomorphicBenchmark.uuid                           avgt    2    12.189          ms/op

```

**Comment by hmottestad** [comment]
At least on this very short benchmark run it didn't seem to make much difference.

**Comment by jeenbroekstra** [comment]
Still useful to know, thanks for trying this. I have some ideas around other ways to make some of this quicker, I just don't have the time right now to pursue them.

**Comment by hmottestad** [comment]
Yeah, thought it was cool. I read about using XOR just the other day on hackernews so wanted to give it a shot. Gonna leave this up here though and maybe I'll come back and run the benchmarks properly. That just takes so much time :(

**Comment by hmottestad** [comment]
I think we need some GC sensitive benchmarks for the isomorphic method.

**Comment by hmottestad** [comment]
Marked this as stale to signal that the PR hasn't been active for a while and that we should consider closing it.

**Pull request closed without merging**
