### PR TITLE
Master to develop merge branch

### PR DESCRIPTION
**Pull request by hmottestad**

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
Why did you need a separate merge branch for this?

**Comment by hmottestad** [comment]
Merge conflicts. This is the only way I know to make jenkins run the tests.

**Comment by jeenbroekstra** [comment]
Let me have a quick look before you merge this. I mean it's fine to do it this way but I want to understand what the conflicts are and if there's perhaps an easier way to handle this in the future.

**Comment by jeenbroekstra** [comment]
Ah I see the conflict - couple of variable renames in RemoteRepositoryManager - so nothing to do with the poms. I typically just do a local merge and conflict resolution, run compliance locally, and then push. But if you prefer handling via a merge branch that's fine. Just be aware that the Jenkins PR verify job does not run full compliance, it only runs the unit tests.

**Comment by jeenbroekstra** [comment]
In retrospect I realize that these kinds of "parallel branch syncs" are probably still better done using merge commits rather than squash and merge....

**Comment by hmottestad** [comment]
Yes. Never squash when merging master into develop.

**Pull request merged**
