### PR TITLE
GH-3931 include lmdb native extensions for distribution

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #3931 

Briefly describe the changes proposed in this PR:

- include LWJGL LMDB native extensions 
- add license blurb to about.md

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
@kenwenzel would appreciate your eyes on this.

**Comment by kenwenzel** [comment]
LGTM!

All native libraries (LWJGL+LMDB) are in sum about 600 kb.

**Comment by hmottestad** [comment]
Should we include Linux arm64?

**Comment by hmottestad** [comment]
@jeenbroekstra @kenwenzel I've added in all the os/architectures I found here: https://www.lwjgl.org/customize

Also bumped version from 3.3.0 to 3.3.1.

**Comment by kenwenzel** [comment]
> @jeenbroekstra @kenwenzel I've added in all the os/architectures I found here: https://www.lwjgl.org/customize
> 
> Also bumped version from 3.3.0 to 3.3.1.

I would exclude the 32-bit architectures.

**Comment by hmottestad** [comment]
Was thinking about the raspberry pi, but I see that they released a 64-bit version in 2016.

**Pull request merged**
