### PR TITLE
4.0.0-M3-release-notes

### PR DESCRIPTION
**Pull request by hmottestad**
Javadocs, release-notes and news item for 4.0.0-M3

### CODE REVIEW

**Comment by hmottestad** [comment]
WIP!

**Comment by jeenbroekstra** [comment]
@hmottestad anything I can do to help this over the line?

**Comment by hmottestad** [comment]
@jeenbroekstra any help would be very welcome. A personal matter has taken a lot of my time and energy and I've been meaning to get back to finishing the release notes. 

I believe that the main task is to summarize the notable changes from M2. I am on the fence about the section on migration and was thinking to remove it entirely and instead reference the notes from M2. 

If you would be able to write the summary of changes then that would  be very helpful. You are also very welcome to finish the notes and news item and merge them in if you have the time.

**Comment by jeenbroekstra** [comment]
No problem, I'll try and find some time today or tomorrow.

**Comment by hmottestad** [comment]
let med just add a note about the SHACL Shapes in user specified graphs

**Comment by hmottestad** [comment]
Thanks @jeenbroekstra . I cancelled the "old" Github Actions CI runs for this branch, so you might get some messages about them having failed.

**Comment by hmottestad** [comment]
Github Actions doesn't have any way to say "only run the tests on the latests commit and cancel any other queued test runs".

**Pull request merged**
