### PR TITLE
GH-3708 Pass JSON-LD writer options to JSON-LD processor

### PR DESCRIPTION
**Pull request by coderkun**
Resolves issue: #3708 

Not only use the JSON-LD writer options for expand/flatten/compact but also for generating the JSON-LD output by passing them to `JsonLdProcessor.fromRDF()`. This will make sure that options like “use native types” will be honored.

----

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
Hi @coderkun, thanks for providing a fix! Could you please digitally sign the Eclipse Contributor Agreement (ECA)? See the [Contributor Guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details on how to sign. Unfortunately, we cannot accept your contribution until these formalities are out of the way. It shouldn't take more than 5-10 minutes to sort out, let me know if you need a hand with anything.

**Review by jeenbroekstra — COMMENTED** [review]
Could you add a test case that demonstrates the problem you're solving?

**Comment by coderkun** [comment]
Thanks for your feedback, @jeenbroekstra. I signed the ECA and added a test as a separate commit.

Please let me know if I should squash both commits together or if there is anything not matching your conventions.

**Comment by jeenbroekstra** [comment]
@coderkun thanks for that! You don't have to squash, that's fine. However it looks as if the code formatter is complaining about your test (not immediately sure why but we've got it set pretty strict). Could you run `mvn process-resources` locally to fix the formatting and amend your last commit?

**Comment by coderkun** [comment]
Thanks again, @jeenbroekstra. I ran `mvn process-resources` and fixed the docstrings for `testNativeRDFTypes()`. Hopefully all tests succeed now …

**Pull request merged**
