### PR TITLE
GH-3535 Upgrade JMH to 1.33

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #3535 

Briefly describe the changes proposed in this PR:
Version bump.

### CODE REVIEW

**Comment by hmottestad** [comment]
I tried 1.32 earlier and had some issues with IntelliJ. I'll give this PR a try when I have time unless it's urgent that you upgrade?

**Comment by JervenBolleman** [comment]
@hmottestad not urgent at all.

**Comment by jeenbroekstra** [comment]
I ran the[ dash license checker](https://github.com/eclipse/dash-licenses) over this and as @barthanssens suggested, 1.33 needs a CQ:

Command:
```
mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES
```

Relevant output

```
maven/mavencentral/org.openjdk.jmh/jmh-core/1.33, GPL-2.0-only WITH Classpath-exception-2.0, restricted, clearlydefined
maven/mavencentral/org.openjdk.jmh/jmh-generator-annprocess/1.33, GPL-2.0-only WITH Classpath-exception-2.0, restricted, clearlydefined
```

Btw if you haven't filed a CQ yet: it seems the dash checker has experimental support for automatically filing a CQ directly from the tool output. See https://github.com/eclipse/dash-licenses#automatic-ip-team-review-requests . Up to you if you want to give that a go while this is still in the experimental stages - the oldfashioned manual CQ is also still accepted of course.

**Comment by jeenbroekstra** [comment]
Btw the jmh CQs are both filed as works-with dependencies (which means that we intend to use the library internally, but not distribute it as part of our releases).

**Comment by JervenBolleman** [comment]
@hmottestad QC's are accepted can I merge this?

**Comment by hmottestad** [comment]
@JervenBolleman I rebased onto develop and force pushed the branch so that it would compile locally on my machine to test it.

**Comment by hmottestad** [comment]
> @hmottestad CQ's are accepted can I merge this?

Just tested locally now and everything works fine! Go ahead and merge once the tests complete.

**Pull request merged**
