### PR TITLE
comment out embedded-elasticsearch dependency and remove all tests

### PR DESCRIPTION
**Pull request by hmottestad**
Related to #1740 

I was unable to get a CQ for the use of the embedded-elasticsearch in our tests. Commenting out the dependency and zipping the tests so we don't cause test failures.

This is a temporary fix.

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra I would like to merge this in before you make the milestone build!

**Comment by jeenbroekstra** [comment]
Thanks for taking care of due diligence on this Havard! Fwiw I'm not actually 100% sure we need to do this before a milestone build (which doesn't count as an official release), but better safe than sorry.

**Comment by hmottestad** [comment]
Messed up the CQ a bit too. I chose source, should have chosen binary. Was looking for works-with, but the CQ system doesn’t use the same words as the CQ docs.

**Comment by jeenbroekstra** [comment]
> Messed up the CQ a bit too. I chose source, should have chosen binary. Was looking for works-with, but the CQ system doesn’t use the same words as the CQ docs.

Yeah, works-with is usually just indicated by adding a comment after you've created the CQ. It's a bit, erhm, manual.

**Pull request merged**
