### PR TITLE
GH-2829 Optimized observations in Changeset

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #2829  

Briefly describe the changes proposed in this PR:

 - new POJO class for keeping observations
 - conversion to old StatementPattern for legacy code

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by hmottestad** [comment]
The changeset could actually use a more optimized datastructure for storing observations.

Since we allow observations with nulls, we know that "null, rdf:type, null" overlaps with "ex:pete, rdf:type, foaf:Person, ex:graph1". Don't really know what this datastructure would would be.

**Review by jeenbroekstra — COMMENTED** [review]
It all looks technically ok, but what exactly is optimized about this? Is it the fact that you've cut out the `Var` objects and keep direct references to the Values?

**Comment by hmottestad** [comment]
We use less memory.

**Comment by hmottestad** [comment]
Less memory usage also means less GC. So technically it's also faster.

**Comment by hmottestad** [comment]
Was also debating making the observations set synchronized. With the ShaclSail we do do parallel reads from a single connection.

**Review by jeenbroekstra — APPROVED** [review]

**Pull request merged**
