### PR TITLE
GH-3396 upgrade solr and lucene

### PR DESCRIPTION
**Pull request by barthanssens**
GitHub issue resolved: #3396 

Briefly describe the changes proposed in this PR:

- upgrade solr and lucene dependencies
- use the "unified" solr highlighter (which will be default in solr 9), since the test fails when using default/original highlighter
- use elasticsearch-maven-plugin instead of elasticsearch-runner
- minor refactoring of tests

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by barthanssens** [comment]
Waiting for CQs to be reviewed, but other than that it should be good to go  (minus a spring version I've updated accidentally)

**Comment by abrokenjester** [comment]
> For some reason the dashlicense tool fails to clear the elasticsearch-high-level-client, looks like the tool receives a JSON response with a misspelled label ("apporoved" instead of "approved")

Can we report that somewhere? 

I haven't looked at the github action in too much detail but if this is the only thing holding us up, can we add it in as a "skip" / "ignore" in its config for now? We can merge regardless of course, but I'd rather not have this error start flaring up for every pull request after - would make the license check useless.

**Comment by barthanssens** [comment]
> > For some reason the dashlicense tool fails to clear the elasticsearch-high-level-client, looks like the tool receives a JSON response with a misspelled label ("apporoved" instead of "approved")
> 
> Can we report that somewhere?
> 
I mentioned it to Rahul (via private chat on the new matrix.eclipse chat room), so hopefully it gets fixed soon

**Comment by barthanssens** [comment]
Hmz ok, now the elastic-search-client is ok, but ES itself is 'restricted', I'll check with Eclipse

**Comment by barthanssens** [comment]
Ok, chatted with Rahul, apparently we can safely ignore the restricted label on ES by the dash tool: it's been marked "approved" in IPlab for our RDF4J use case

**Comment by barthanssens** [comment]
For good measure, I'll add a few lines on the ES-licensing on the website https://rdf4j.org/documentation/reference/configuration/#elasticsearch-store

**Review by hmottestad — APPROVED** [review]

**Pull request merged**
