### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### eclipse/rdf4j now has a Chat Room on Gitter

@jeenbroekstra has just created a chat room. You can visit it here: [https://gitter.im/eclipse/rdf4j](https://gitter.im/eclipse/rdf4j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/eclipse/rdf4j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://gitlab.com/gitlab-org/gitter/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
This is low effort to set up, and I like the notion of having a more casual "chat like" forum both for ourselves and for the wider community. The risk is that it turns into a graveyard a bit. How do you feel about using gitter as a chat forum? 

Advantages:
1. gitter is open source
2. discoverability, compared to mattermost (on eclipse's own server): gitter.im is global, anybody who searches for "rdf" will see our chat room
3. signup is simple: github, twitter or facebook id. 
4. runs from your browser or mobile.

Disadvantage:
1. we've tried chat rooms before and it never really took off (too hard to find and/or not enough interest)
2. we will need to regularly check the channel to keep it relevant

Thoughts? 

PS this came about because of a twitter discussion where someone asked for more "casual" environment (like Slack) to talk shop around RDF in general, and tools like RDF4J specifically.

**Comment by hmottestad** [comment]
I think it’s a good idea to try. Also a bit lower threshold since you can sign in with GitHub. 

I don’t think I would take the time to visit unless someone specifically directed me for a chat. As much as I hate the google groups interface, I find it really easy to keep connected when it sends me summary emails when there is any activity.

**Comment by jeenbroekstra** [comment]
> I don’t think I would take the time to visit unless someone specifically directed me for a chat. As much as I hate the google groups interface, I find it really easy to keep connected when it sends me summary emails when there is any activity.

Fwiw I believe gitter does have an e-mail notification mechanism that you can fine-tune. Haven't actually tried it yet though.

**Comment by barthanssens** [comment]
Nice, I hadn't heard of gitter chat before, so I learned something new today :-)

Looks quite good actually, the only thing that could be somewhat disturbing is the amount of read-permissions gitter needs when signing up / logging in using Twitter or GitHub (though reading the documentation, it looks like it's actually not a gitter issue, but the lack of fine-grained permissions on said platforms...)

**Pull request merged**
