### PR TITLE
GH-4119 LMDB store in Workbench

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #4119 

Briefly describe the changes proposed in this PR:

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
@kenwenzel you can try this out by checking out my branch and going to the `docker` directory and running `./build.sh` followed by `docker-compose up -d` and then go to `http://localhost:8080/rdf4j-workbench`.

**Comment by hmottestad** [comment]
@jeenbroekstra i want to merge the changes that allow the LMDB store to be created from the workbench, since I thought that this had already been included in RDF4J 4.1.0 so I put it in the release announcement. 

The other changes, which are more performance related I'll retarget to 4.2.0 together with config options in the workbench for LMDB and SHACL/RDFS/etc.

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra i want to merge the changes that allow the LMDB store to be created from the workbench, since I thought that this had already been included in RDF4J 4.1.0 so I put it in the release announcement.

Sounds good. I had a glance at the PR and it looks legit. Have you had a chance to run the changes in the workbench and check that it works?

> The other changes, which are more performance related I'll retarget to 4.2.0 together with config options in the workbench for LMDB and SHACL/RDFS/etc.

👍

**Comment by hmottestad** [comment]
Yeah. I use the docker script to run it up. Works well.

**Pull request merged**
