### PR TITLE
GH-2544 Java 15

### PR DESCRIPTION
**Pull request by hmottestad**
Signed-off-by: hmottestad <hmottestad@gmail.com>

GitHub issue resolved: #2544  

Briefly describe the changes proposed in this PR:

Support Java 15.

---- 
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by hmottestad** [comment]
This is currently failing since spin uses the js script engine (nashorn?) and it was removed in java 15.

**Comment by hmottestad** [comment]
@jeenbroekstra we need to bump the maven build plugin, I think I remember that we don't need to do CQs for that anymore.

**Comment by hmottestad** [comment]
Looks like the merge block is stopping us from merging this because it is expecting a build for java 14. So we are going to have to disable the merge block if we don't want to build on both 8, 14 and 15!

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra we need to bump the maven build plugin, I think I remember that we don't need to do CQs for that anymore.

That depends - we have a single "list" CQ that covers these kinds of dependencies, usually with a version-range for each one. See https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20318. I see it's the bundle plugin you're updating, which is covered up to version 4.2.0, but you're bumping to 5.1.1, so it's not covered. 

I will get in touch with the IP team on how to log these kinds of things, as I am not sure how we are supposed to update that list CQ.

**Comment by jeenbroekstra** [comment]
> Looks like the merge block is stopping us from merging this because it is expecting a build for java 14. So we are going to have to disable the merge block if we don't want to build on both 8, 14 and 15!

Ah, that is a pain. I'll ask them to update the settings so that only the 1.8 build is actually required, gives us a bit more flexibility in the future.

**Comment by jeenbroekstra** [comment]
Branch protection has been adapted.

**Comment by jeenbroekstra** [comment]
> This is currently failing since spin uses the js script engine (nashorn?) and it was removed in java 15.

Out of curiosity: what does the spin implementation use a javascript engine for?

**Comment by hmottestad** [comment]
I think users can implement transformations of data using JS in SPIN functions. Haven't looked more into it though, so not sure. 

I know TopQuadrant are doing something similar in their SHACL implementation by using GraalVM. I assume that was due to people using the JS support in SPIN.

**Review by jeenbroekstra — APPROVED** [review]

**Pull request merged**
