### PR TITLE
GH-2442 further performance improvements for ValueComparator

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #2442  

Briefly describe the changes proposed in this PR:

- use Hashsets to do faster datatype comparison when determining if a URI is a numeric/calendar/etc datatype
- modified benchmark setup to be able to run from command line

---- 
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
#### Before

```
Benchmark                                       Mode  Cnt    Score   Error  Units
ValueComparatorBenchmark.sortManyDeepEquals     avgt   10  290.611 ± 6.316  ms/op
ValueComparatorBenchmark.sortManyPointerEquals  avgt   10   97.072 ± 2.472  ms/op
ValueComparatorBenchmark.sortObjects            avgt   10  147.607 ± 3.358  ms/op
ValueComparatorBenchmark.sortPredicates         avgt   10    0.066 ± 0.001  ms/op
ValueComparatorBenchmark.sortSubjects           avgt   10   57.832 ± 2.292  ms/op
```

**Comment by jeenbroekstra** [comment]
#### Using HashSets

```
Benchmark                                       Mode  Cnt    Score   Error  Units
ValueComparatorBenchmark.sortManyDeepEquals     avgt   10  272.526 ± 4.734  ms/op
ValueComparatorBenchmark.sortManyPointerEquals  avgt   10   87.609 ± 1.806  ms/op
ValueComparatorBenchmark.sortObjects            avgt   10  111.398 ± 1.589  ms/op
ValueComparatorBenchmark.sortPredicates         avgt   10    0.067 ± 0.001  ms/op
ValueComparatorBenchmark.sortSubjects           avgt   10   58.201 ± 1.423  ms/op
```

 24% improvement on sorting objects. The other improvements are less significant or zero, which makes sense as they (also) look at subject/predicates (which can't be literals).

**Comment by jeenbroekstra** [comment]
I enjoyed that by the way. Happy with the fact that I've now got an easy way to use benchmarks.

**Comment by hmottestad** [comment]
Good to hear you enjoyed it :) It's a great simple fix too 😀

**Pull request merged**
