### PR TITLE
Issue #164: configurable eval strategy

### PR DESCRIPTION
**Pull request by pulquero**
This PR addresses GitHub issue: #164 

Briefly describe the changes proposed in this PR:

- ...
- ...
- ...

Make sure you've followed the [Contributor Guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md). In particular (please tick to indicate you've taken care of it):

- [x] RDF4J code formatting has been applied
- [x] all tests succeed

Signed-off-by: Mark Hale <mark.hale@physics.org>

### CODE REVIEW

**Comment by pulquero** [comment]
*sigh* yet another git disaster. Anyway, I managed to rescue it.

**Comment by pulquero** [comment]
Previous comments and replies here: https://github.com/eclipse/rdf4j/pull/224

**Comment by jeenbroekstra** [comment]
@pulquero is there any way I can help you prevent these git problems occurring? I'm assuming that the root cause is that you occasionally forget to check you're working on the correct branch and/or sync with the master repo?

**Comment by pulquero** [comment]
I think I'm just cursed or maybe it is old age creeping up on me. I've established one thing, I prefer bitbucket to git. So, yes, I sometimes branch from the wrong branch or merge in the wrong branch. Maybe I should include the target branch in the branch name see if that helps. This time though, eclipse lost my author setting and I autocompleted with the wrong email address. That mixed up with merging in the wrong target branch at some stage maybe it difficult to sort out the history to fix ip validation. Anyway, reflog and cherry picking to the rescue.

**Comment by jeenbroekstra** [comment]
Fair enough :) If it might help, we could adapt our workflow to use the source branch as part of the branch naming. Currently we prefix with 'issues/' only. We could adopt something more elaborate, e.g. 'hotfixes/' (for issues on the release branch) and 'features/' for any enhancements on the main dev branch. Anyway, getting offtopic here, let's continue this on the mailinglist.

**Comment by jeenbroekstra** [comment]
There's a merge conflict with this PR, can you take a look at this @pulquero ?

Other than that: due to the long timeframe (and the multiple PRs) I kinda lost track where we are with this. I had a quick glance at the code and it looks fine to me. Do you consider this stable and ready for release as-is?

Also: given that we want to use this mechanism to disable/enable extended features such as extended datetime comparison (see #163 ), can you give some short pointers on what should happen in the PR for that issue to get it to work in extended mode but not in strict?

**Comment by pulquero** [comment]
Yep, I consider it ready. So for #163, I imagine there would be an extended eval strategy subclass of simple eval strategy which overrides the relevant methods (I think most of them are private atm). There would then be an associated extended eval strat factory which can be set on a sail to use it. It can also be added to the create-*.xsl to allow it to be chosen in workbench.

**Comment by jeenbroekstra** [comment]
Running hudson: https://hudson.eclipse.org/rdf4j/job/rdf4j-verify-pr/28/

**Comment by jeenbroekstra** [comment]
Hudson succeeds.

**Pull request merged**
