### PR TITLE
GH-4405: Migrate parameterized tests to JUnit 5

### PR DESCRIPTION
**Pull request by erikgb**
GitHub issue resolved: #4405 

Briefly describe the changes proposed in this PR:

This PR migrates most of the parameterized tests to JUnit 5. Some SPARQL compliance tests are still remaining, as they have an even more complicated setup. Especially for ignoring specific tests. I will take a look at this, and suspect I will need a pre-PR before it is possible to migrate the remaining parameterized tests.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by erikgb** [comment]
@abrokenjester Any idea why the ECA job is suddenly failing on this PR? I might have something screwed up in my local git config, but I am unable to see what.

**Comment by abrokenjester** [comment]
I think it's the check itself, I saw the same thing on one of my own PRs.

**Comment by erikgb** [comment]
> I think it's the check itself, I saw the same thing on one of my own PRs.

Ok, thanks! How did you fix it? Create a new PR?

**Comment by erikgb** [comment]
@abrokenjester NVM, I found an issue in my local Git setup. Looks better now.

**Comment by hmottestad** [comment]
I think that maybe this should be targeted at develop instead of main since it's not strictly a bug fix.

**Comment by erikgb** [comment]
> I think that maybe this should be targeted at develop instead of main since it's not strictly a bug fix.

I happy to do as you prefer, but this (and similar PRs) are just updating test sources. Is the branch model documented somewhere?

**Comment by abrokenjester** [comment]
> > I think that maybe this should be targeted at develop instead of main since it's not strictly a bug fix.
> 
> I happy to do as you prefer, but this (and similar PRs) are just updating test sources. Is the branch model documented somewhere?

Good point by @hmottestad. I hadn't thought of it, but the modules in `testsuite/` are, strictly speaking, production code as they are released as reusable modules for 3rd party implementations of e.g. SAILs to use for compliance checking.

As for the branching model, it's explained here: https://rdf4j.org/documentation/developer/workflow/ . Though we are currently in a bit of an odd situation in that we have _third_ long-term branch for tracking 5.0 development.

**Comment by abrokenjester** [comment]
Following up on this: what I said above is true but I just realised we already merged another PR with JUnit 5 upgrades to main, and that PR also contained changes to the testsuites. @hmottestad given that that's the case I suggest that instead of rebasing these open PRs against develop we just go with it and push it through on main. If we get complaints we'll do our best to help them migrate.

**Pull request merged**
