### PR TITLE
GH-2604 rdfstar transaction bug

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #2604  

Briefly describe the changes proposed in this PR:

- fixed transactional handling of RDF* triple retrieval in Memory Store
- added regression tests

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra I wasn't planning on fixing this, just to reproduce the issue.

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra I wasn't planning on fixing this, just to reproduce the issue.

Thanks @hmottestad , I'll continue on this branch to look at a fix when I can find the time.

**Comment by jeenbroekstra** [comment]
I haven't forgotten. It just turns out to be a pain to track this down. Too many wrapped iterators :(

**Comment by hmottestad** [comment]
I get your pain. Maybe take a look at the SPARQL query plan?

**Comment by jeenbroekstra** [comment]
> I get your pain. Maybe take a look at the SPARQL query plan?

I've pinpointed the issue, it comes down to the SailDatasetImpl not dealing with uncommitted changes properly in the case of RDF* triples. There is a TODO indicating that this is an issue there.

Fixing it is not trivial as I'll need to figure out a way not just to see which triples have been added/removed, but also which ones are no longer present at all in the database as a consequence of being removed (the same triple can have multiple occurrences, e.g. as the subject of several statements). 

Fortunately, the memory store naturally indexes this kind of thing so I think it's not a _huge_ effort to fix it in the end - it just requires some patient digging.

**Comment by jeenbroekstra** [comment]
I've managed to add a fix for this that is probably not optimal in terms of performance, but functionally correct (knock on wood). At this stage of RDF* support I believe that to be acceptable (especially since currently only the memory store actually supports any of this).

**Pull request merged**
