### PR TITLE
GH-2061 on top of GH-3843, new collection factory on top of MapDb3 wi…

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: #2061
Briefly describe the changes proposed in this PR:
This introduces a new collection factory backed by mapdb3.
However, at this point it is a new option and not yet configured or used by any specific sail.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@barthanssens as you looked at upgrading to MapDB v3 last, this is part of how the upgrade would look using the collection-factory-api approach.

**Comment by barthanssens** [comment]
Thanks Jerven. Last time I've checked, the performance of MapDB 3.0 was less than v1.0 for our purposes... is this still the case ?

**Comment by JervenBolleman** [comment]
With a bit more code this can be made about twice as fast. Mostly by being smarter in the serialization logic.
At this point I wanted to show a minimal patch before adding all that complication.

**Comment by JervenBolleman** [comment]
@barthanssens  would you mind having a look now? MapDb3 is not enabled by default now. But I think with the serializer changes this will be faster than before.

**Comment by JervenBolleman** [comment]
So the main difference in performance in mapdb1/3 is the change of per default not using a mmap'ed backing file.

Re-enabling those is the difference is in favor of the MapDB3 version as implemented.

**Comment by JervenBolleman** [comment]
@hmottestad FYI I hope to merge this once 4.3.0 is out of the door. While not enabled by default, I think it is best to not include last minute additions in the 4.3.0 release.

**Pull request merged**
