### PR TITLE
GH-3769 make RepositoryController extensible

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3769  

Briefly describe the changes proposed in this PR:

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
I haven't looked in detail yet but why exactly do you want to extend this?

**Comment by hmottestad** [comment]
Ontotext extends this in their code base, but there are no extensions points and they end up replicating all our functionality in order to add support for some very minor modifications.

I should probably have marked this at WIP, since I've still got some work to do.

**Comment by jeenbroekstra** [comment]
Fwiw had a glance through your changes sofar, and looks like a solid refactor to me. Some of this setup hasn't been touched in years, so high time someone took a duster through it :)

**Comment by hmottestad** [comment]
@jeenbroekstra if all the tests pass I intend to merge this and publish the milestone build tomorrow. Is that ok with you?

**Comment by jeenbroekstra** [comment]
Sounds good to me!

**Pull request merged**
