### PR TITLE
Issues #565 Bug fixes for TupleFunctionEvaluationStrategy.

### PR DESCRIPTION
**Pull request by pulquero**
This PR addresses GitHub issue: #565  .

Briefly describe the changes proposed in this PR:

* Fixes problems in TupleFunctionEvaluationStrategy.
* 
* 

Signed-off-by: Mark Hale <mark.hale@physics.org>

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
Started hudson build for this PR: https://hudson.eclipse.org/rdf4j/job/rdf4j-verify-pr/21/

**Comment by jeenbroekstra** [comment]
Hudson reports failing tests:

```
Failed tests: 
  EvaluationModeTest.testServiceEvaluationMode:37->testEvaluationMode:61 variable already bound: t
  EvaluationModeTest.testTripleSourceEvaluationMode:44->testEvaluationMode:61 variable already bound: t
```

**Comment by pulquero** [comment]
Didn't have assertions on first-time round.

**Comment by jeenbroekstra** [comment]
Doing new hudson run: https://hudson.eclipse.org/rdf4j/job/rdf4j-verify-pr/24/

**Comment by jeenbroekstra** [comment]
All succeeded.

**Pull request merged**
