### PR TITLE
GH-1792 refactor test jars

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #1792  

Briefly describe the changes proposed in this PR:

* got rid of test-jars which caused endless build loops
* re-introduced testsuites for repository api, sail-api and model api
* testsuites are used by unit tests where appropriate (instead of just being for compliance testing)
* compliance tests now run again in default build profile

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
Grmbl. The rio compliance tests are giving me grief. I may need to roll that part back.

**Comment by jeenbroekstra** [comment]
This is mostly a reorganization so I'm not expecting a line-by-line code review, but I'm hoping you can give it a glance, perhaps take the branch for a quick test spin locally, etc, and if anything is unclear or you spot any issues I'd like to hear it!

**Comment by hmottestad** [comment]
```
2019-12-31T08:43:58.7814108Z [INFO] Running org.eclipse.rdf4j.sail.shacl.MultithreadedNativeStoreTest
2019-12-31T08:43:58.9590146Z 08:43:58.958 [pool-16704-thread-1] ERROR ShaclSail was garbage collected without shutdown() having been called first.
2019-12-31T08:43:58.9669635Z 08:43:58.966 [pool-16708-thread-1] ERROR ShaclSail was garbage collected without shutdown() having been called first.
2019-12-31T08:43:58.9827174Z 08:43:58.982 [pool-16709-thread-1] ERROR ShaclSail was garbage collected without shutdown() having been called first.
2019-12-31T14:20:28.9807288Z ##[error]The operation was canceled.
2019-12-31T14:20:28.9828049Z Cleaning up orphan processes
2019-12-31T14:20:28.9947130Z Terminate orphan process: pid (9480) (java)
2019-12-31T14:20:28.9958555Z Terminate orphan process: pid (26678) (sh)
2019-12-31T14:20:28.9962877Z Terminate orphan process: pid (26680) (java)
```

I believe I might not have fixed this on master, just develop.

**Comment by hmottestad** [comment]
Rerunning checks now.

**Comment by jeenbroekstra** [comment]
Fwiw this is rather a blocker for me personally, since without these changes my Eclipse IDE goes haywire on the maven build. I'll probably merge this in quickly after a few more tests on my end (i'll also give IntelliJ a spin on this to make sure I don't block Havard) - if any further problems crop up we can deal with them as we go. 

I also have it in my head to write a bit of developer documentation that goes into the details of our maven setup, why it's organized the way it is, where to find/place different kinds of tests, etc.

**Pull request merged**
