### PR TITLE
GH-4167 - Fixing datafiles for SPARQLQueryComplianceTest

### PR DESCRIPTION
**Pull request by nguyenm100**
Results of some tests were incorrect and always failing when compared to actual from SPARQLQueryComplianceTests.  This PR is to patch those results.

### CODE REVIEW

**Comment by hmottestad** [comment]
Could you help me out a bit by explaining how I can easily run these tests locally on my laptop?

**Comment by nguyenm100** [comment]
Hi, I'm using a fork of Halyard (by @pulquero) who has wired up a lot of these tests.  You can see them here: https://github.com/pulquero/Halyard/blob/latest/strategy/src/test/java/com/msd/gin/halyard/strategy/HalyardSPARQLQueryTest.java

**Comment by jeenbroekstra** [comment]
The problem is that the testcases in the `testcases-sparql-1.1` directory are no longer in use in RDF4J itself. It was originally intended as an extension of official W3C test cases with our own additions for as we discovered them, but it quickly become too cumbersome to maintain that. 

We have switched our own testing framework for SPARQL over to the `RepositorySPARQLComplianceTestSuite`, which is not based on an manifest-based set of test data. `SPARQLQueryComplianceTest` is only still in use for running the W3C-approved manifest suites for SPARQL 1.0 and 1.1 compliance (which are in the `testcases-sparql-1.0-w3c` and `testcases-sparql-1.1-w3c` directories).

I have no objection to this PR (though I haven't checked the tests yet to see if the fixes make sense) but the real fix is that we just get rid of this old datadir and advise anyone still using it to switch to `RepositorySPARQLComplianceTestSuite` (which is much easier to work with anyway).

**Review by jeenbroekstra — APPROVED** [review]

**Comment by nguyenm100** [comment]
Is RepositorySPARQLComplianceTestSuite wired up as part of the rdf4j build and does it carry over the tests from test-cases-sparql-1.1?  I ask b/c the tests in that directory flagged some issues that were recently fixed see: https://github.com/eclipse/rdf4j/issues/4165 & https://github.com/eclipse/rdf4j/issues/4164

and another issue I'll be reporting in a sec.

**Comment by nguyenm100** [comment]
see: https://github.com/eclipse/rdf4j/issues/4209

**Comment by jeenbroekstra** [comment]
> Is RepositorySPARQLComplianceTestSuite wired up as part of the rdf4j build and does it carry over the tests from test-cases-sparql-1.1? I ask b/c the tests in that directory flagged some issues that were recently fixed see: #4165 & #4164

It is wired up as part of the build. Whether it completely covers all possible test cases in that old directory I don't know, but probably not. If you spot lack of coverage it might be good to port them over.

**Pull request merged**
