### PR TITLE
GH-2741 Avoid redoing work that can be done once per query for each evaluation.

### PR DESCRIPTION
**Pull request by JervenBolleman**
GitHub issue resolved: # GH-2741 in part

Briefly describe the changes proposed in this PR:

Introduce a `QueryEvaluationStep` interface and a `prepare` method in the `EvaluationStrategy`.
The idea of the prepare step is that it prepares an step required in the evaluation in the query as much as possible.
This allows us to decouple setup code from evaluation code.
It is also a first step into breaking up the gigantic `StrictEvaluationStrategy` into many smaller classes.

For example I took out from the StrictEvaluationStrategy the logic for the StatementPattern evaluation and moved it into a new class StatementPatternIteration. This `StatementPatternIteration` implements the interface `QueryEvaluationStep`. A lot of work
that is otherwise evaluated per invocation of evaluate is now done in the constructor. For example determining if the query needs to look into the Sparql Dataset can be done once instead of at each invocation. I also used this for effect in two join operators.

This allows for performance improvements. I moved the complexQuery benchmark from the native store into the memory store code (not part of this PR)

This PR
```
Benchmark                                               Mode  Cnt     Score    Error  Units
QueryBenchmark.complexQuery                             avgt   10  1364.842 ± 11.844  ms/op
QueryBenchmark.groupByQuery                             avgt   10     8.081 ±  0.198  ms/op
QueryBenchmark.pathExpressionQuery1                     avgt   10    75.376 ±  0.646  ms/op
QueryBenchmark.pathExpressionQuery2                     avgt   10     8.196 ±  0.398  ms/op
QueryBenchmark.removeByQuery                            avgt   10     9.227 ±  0.563  ms/op
QueryBenchmark.removeByQueryReadCommitted               avgt   10    28.489 ±  1.402  ms/op
QueryBenchmark.simpleUpdateQueryIsolationNone           avgt   10   140.449 ±  1.763  ms/op
QueryBenchmark.simpleUpdateQueryIsolationReadCommitted  avgt   10   198.569 ±  4.737  ms/op
```

Develop  
```
Benchmark                                               Mode  Cnt     Score     Error  Units
QueryBenchmark.complexQuery                             avgt   10  1550.240 ± 161.524  ms/op
QueryBenchmark.groupByQuery                             avgt   10     9.595 ±   1.293  ms/op
QueryBenchmark.pathExpressionQuery1                     avgt   10    78.985 ±   1.840  ms/op
QueryBenchmark.pathExpressionQuery2                     avgt   10     8.028 ±   0.086  ms/op
QueryBenchmark.removeByQuery                            avgt   10     9.179 ±   0.418  ms/op
QueryBenchmark.removeByQueryReadCommitted               avgt   10    27.527 ±   0.826  ms/op
QueryBenchmark.simpleUpdateQueryIsolationNone           avgt   10   136.287 ±   1.381  ms/op
QueryBenchmark.simpleUpdateQueryIsolationReadCommitted  avgt   10   202.415 ±   2.315  ms/op
```

This already gives a nice performance benefit at 13% faster at evaluating complex queries.

The fact that setup logic is cheaper because executed less often will allow the ideas of #GH-2742 to work nicely and improve performance across the board.

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@jeenbroekstra  @hmottestad @barthanssens this is finally ready for review. It became super intrusive so lets have a good look at this.

**Comment by JervenBolleman** [comment]
I still don't understand why the compliance test started failing.

**Comment by hmottestad** [comment]
Btw. I started testing out your changes are found some MemoryStore specific optimizations that I've collected here: https://github.com/eclipse/rdf4j/pull/3411

**Comment by JervenBolleman** [comment]
I made a [new clean branch with only commits related to this feature](https://github.com/eclipse/rdf4j/pull/3518), rebased on develop. To make it easier to review. Closing this pull request but all comments where taken into account.

**Pull request closed without merging**
