### PR TITLE
GH-2065 FedX implements NotifyingSail

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: # 2065 

Briefly describe the changes proposed in this PR:

FedX implements NotifyingSail, FedXConnection implements NotifyingSailConnection.

This is a draft.

---- 
PR Author Checklist: 

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by hmottestad** [comment]
Do you reckon this then could be wrapped in a ShaclSail for remote SHACL validation?

**Comment by jeenbroekstra** [comment]
> Do you reckon this then could be wrapped in a ShaclSail for remote SHACL validation?

That is the idea. I'm suspecting there will be other hurdles though - I've done a quick initial spike and could get it to work on an initially empty backend store, but it fell over if I started with data already in it.

**Comment by hmottestad** [comment]
Was that due to performance issues?

**Comment by hmottestad** [comment]
Also wondering, does FedX support adding/removing data? How does it know where to route it to?

**Comment by aschwarte10** [comment]
> Also wondering, does FedX support adding/removing data? How does it know where to route it to?

This is currently an experimental feature and can be done on the code-level by setting one Endpoint (i.e. federation member) to writable. If this is the case we activate a simplistic write-strategy that just passes the write operation on to the target member.

Note that the implementation is currently really basic. There is more work planned on this in the mid-term (e.g. something like grouping statements before pushing them to the federation member).

**Comment by jeenbroekstra** [comment]
I will likely park this for a bit - it doesn't have high priority and there some thorny issues with it, I don't want to get entangled in.

**Pull request closed without merging**
