### PR TITLE
GH-2011 back to merge-commits as our preferred strategy

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #2011   

Briefly describe the changes proposed in this PR:

- back to specifying 'merge-commit' as our PR merge strategy

---- 
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
I briefly thought about also adding rebase again as a merge option, and while I would personally like it, I think in the end we're better off just keeping it simple, and doing everything using merge-commits.

**Comment by hmottestad** [comment]
It's fine with me. Do you have any tips for squashing a branch together that has develop merged into it several times?

**Comment by jeenbroekstra** [comment]
> It's fine with me. Do you have any tips for squashing a branch together that has develop merged into it several times?

I think this is only a problem if there are merge conflicts involved. In any case, the simplest way to deal with it is probably to use rebase instead of merge to bring your branch up to date with develop. Also has the advantage of making the history easier to read after your branch has been merged back.

**Comment by hmottestad** [comment]
Bit late to start rebasing it now. Haven't bothered much with rebasing since we squash and merge anyway.

**Comment by jeenbroekstra** [comment]
> Bit late to start rebasing it now. Haven't bothered much with rebasing since we squash and merge anyway.

I'm fine with still using squash and merge for your existing feature branch. Just for any future work, we go back to manual squash + merge commit.

**Comment by hmottestad** [comment]
We can probably keep both methods. For our own work we can squash and merge if we want, while for other committers we use normal merge.

**Comment by jeenbroekstra** [comment]
> We can probably keep both methods. For our own work we can squash and merge if we want, while for other committers we use normal merge.

I thought of that, but it makes things more error-prone, having two separate merge methods in play. Also, there is a fundamental problem with git overwriting the author field that can affect core committers as well. 

So I'm really not in favour of keeping squash-and-merge as an option.

**Pull request merged**
