### PR TITLE
Issues/1618 assertion error in abstract sail connection

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #1618

Briefly describe the changes proposed in this PR:

 - Added synchronization to flushPendingUpdates() because this method is called from read operations and should be thread safe. The federation sail has a parallel join operation that assumes the all read operations against the base sails are thread safe.

### CODE REVIEW

**Comment by hmottestad** [comment]
Need to run compliance tests.

**Comment by hmottestad** [comment]
@jeenbroekstra @ieurich this is my proposed fix. I have a good test based on code from @ieurich that reproduces the issue every time on my laptop. The issue is some multithreaded use of the same base connection by the FederationSail, this triggers a race condition because not all "read" methods are thread safe. There might still be more issues, as I've discovered during my ShaclSail development, but I think synchronizing flushPendingUpdates() should do the trick for this particular issue.

**Comment by hmottestad** [comment]
@jeenbroekstra can i merge this?

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra can i merge this?

Yep, lgtm, sorry for the delay.

**Comment by jeenbroekstra** [comment]
@hmottestad  Don't forget to squash!

**Pull request merged**
