### PR TITLE
merge master into develop

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: # 

Briefly describe the changes proposed in this PR:

---- 
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by hmottestad** [comment]
Screenshot 2020-09-15 at 17 15 41

@jeenbroekstra you know what this is supposed to mean? I don't understand how it can be out of date.

**Comment by jeenbroekstra** [comment]
It looks as if when the Eclipse admins enabled branch protections for us, they also enabled "Require branches to be up to date before merging". That's not something I actually wanted, so I've asked them to fix that. 

Why it shows it in this case is purely that develop contains several commits that are not on master (which is of course not suprising). The check is designed for feature branches (making sure that the feature branch works against the latest version of the code), not for long term parallel release branches. But as said, I've asked them to disable this check again.

**Comment by jeenbroekstra** [comment]
That additional check has been disabled again, but now we're getting intermittent build failures on downloading the javax.annotations dependency from central. Grmbl. Restarting the build seems to _eventually_ solve that, but I wish there was a better solution.

**Comment by hmottestad** [comment]
I tried to enable caching of dependencies between builds to work once. Might take a look at that again.

**Comment by jeenbroekstra** [comment]
I believe eclipse also run a proxy maven repository, perhaps we can make use of that. I'll have to look up the details though.

**Comment by jeenbroekstra** [comment]
@hmottestad I've opened a new ticket (#2510 ) for the dependency caching. Looks like github has some pretty good support for this kind of thing.

**Pull request merged**
