### PR TITLE
GH-3350 update pom and docker to support jdk17

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #2046 
GitHub issue related: #3350 

Briefly describe the changes proposed in this PR:

 - updated some build plugins that don't work on jdk17 (versions already covered by CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20318 )
 - updated base docker image to jre11 which we need because we are targeting 11 with our compiler (using the docker image is the only way I know to test that I didn't break the war file)

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
@JervenBolleman I couldn't add you as a reviewer for this PR, but thought you might like to take a look.

**Comment by hmottestad** [comment]
Do we need a CQ for the docker base image update?

**Comment by jeenbroekstra** [comment]
> Do we need a CQ for the docker base image update?

I don't think we did one for the original, so let's leave it for now.

**Comment by jeenbroekstra** [comment]
> updated base docker image to jre11 which we need because we are targeting 11 with our compiler (using the docker image is the only way I know to test that I didn't break the war file)

What I typically do is build the war using `mvn -Passembly package` and then drop it in a locally running tomcat server. I could imagine direcly running a docker image being easier though.

Could you share (perhaps as a writeup in the developer docs) how you use the docker image to test? What I mean is literally just the commands you use to produce the docker image and then run it. It's probably straightforward enough but we have almost zero documentation around our docker images, and this might be a good place to start.

**Comment by hmottestad** [comment]
I use the bash script called build.sh and then I run "docker-compose up".

**Comment by hmottestad** [comment]
I think there are some readme files in the same directory. Probably the biggest improvement would be to move the docker stuff to its own directory to increase visibility.

**Comment by barthanssens** [comment]
> Do we need a CQ for the docker base image update?

IIRC this wans't necessary, because docker builds are not 'official' Eclipse deliverables (though memory could serve me wrong)

**Comment by barthanssens** [comment]
> I think there are some readme files in the same directory. Probably the biggest improvement would be to move the docker stuff to its own directory to increase visibility.

Back in the days I wrote some stuff on the dev mailinglist as well...
Which reminds me I'll have to push the images to hub.docker.com... (at one point we were looking into doing this automatically)

**Comment by hmottestad** [comment]
Related: #3389

**Pull request merged**
