### PR TITLE
Fix #69: IRI Parser for validation and resolution

### LINKED ISSUE #69: Provide utility methods for IRI validation
(Migrated from https://openrdf.atlassian.net/browse/SES-2191 )

We should provide utility methods to allow checking that a given string is a valid IRI according to RFC3987.

### PR DESCRIPTION
**Pull request by jamesrdf**
This PR addresses GitHub issue: #69 .

Briefly describe the changes proposed in this PR:

* Creats ParsedIRI for RFC 3987 IRI syntax validation
* Deprecates ParsedURI in favor of ParsedIRI

### CODE REVIEW

**Comment by jamesrdf** [comment]
I have since run some performance tests against ParsedIRI and then in lined some common character checks to speed it up a bit. ParsedURI is still faster though, since ParsedIRI also validates characters when parsing.

**Comment by jeenbroekstra** [comment]
@grexe you currently do, yes. Part of the reason is simply that `ParsedIRI` is defined in the `rdf4j-util` library, while the `IRI` class is defined in the `rdf4j-model` library, which is dependent on `rdf4j-util`. We can't use the `IRI` class in `rdf4j-util` without introducing a cyclic dependency.

**Comment by grexe** [comment]
Ok I see, thanks for clarification @jeenbroekstra, but wouldn't it make more sense to move `ParsedIri` next to `IRI` then?

**Comment by jeenbroekstra** [comment]
Possibly. I don't think use outside of direct internal usage by the parsers was really envisioned, which is why it is where it is. But feel free to log a feature request for this, and we can take a look at it.

**Pull request merged**
