### PR TITLE
GH-2654: initial pom for Jib/Jetty/JDK11

### PR DESCRIPTION
**Pull request by barthanssens**
Signed-off-by: Bart Hanssens <bart.hanssens@bosa.fgov.be>

GitHub issue resolved: #2654  

Briefly describe the changes proposed in this PR:
- use Google JIB to create docker images without docker daemon, and push images to hub.docker.io
- ARM and Intel 64-bit in one push
- version + latest tag
- use JRE 11 instead of JRE 8
- use Jetty 9.4 instead of Tomcat

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by barthanssens** [comment]
Current issues:

- no HTTPS yet
- for testing purposes, uses my hub docker instead of Eclipse's
-  uses stock Jetty 9.4.33 images, but RDF4J build has issues with Jetty 9.4.24+ (some tests fail)
- Jib does not work (by design) in a pom.xml with package "pom", hence the need for a dummy submodule / pom.xml and a dummy target/classes directory

**Comment by jeenbroekstra** [comment]
> Current issues:
> 
> * no HTTPS yet

You mean for the actual jetty server being run in the docker container we produce? I don't think the currently manually produced one supports that either, right? Let's treat that as a separate feature request.

> * for testing purposes, uses my hub docker instead of Eclipse's

How does this plugin authenticate itself with dockerhub? Does it require that you are logged through a `docker login` command or something? 

Also, what maven commands do you use to actually build the docker images, and push them? It would be ideal if we could separate these out btw, so that, for example, we can build docker images locally for snapshots without pushing them to dockerhub. 

> * uses stock Jetty 9.4.33 images, but RDF4J build has issues with Jetty 9.4.24+ (some tests fail)

To separate that out, can we (temporarily) just use a slightly older image, until we've gotten to the root of the test failure issues?

> * Jib does not work (by design) in a pom.xml with package "pom", hence the need for a dummy submodule / pom.xml and a dummy target/classes directory

That's really strange. Why would the packaging type of the module have any influence on whether or not the plugin gets executed? 

That being said I don't object to a separate module for this, if that's the easiest way to get it set up, though I'm a little uncomfortable with it sitting at the project root level. We could have a quick look at reorganizing our assembly module a little, perhaps turn it into a set of submodules (sdk, onejar, docker).

**Comment by barthanssens** [comment]
Indeed, currently there is no HTTPS version for our Tomcat image either.

mvn jib:build should do the trick, though it requires at least a dummy target/classes directory to be present (so mvn clean messes that up)

Pushing indeed relies on e.g. docker login, though other options are available: https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#authentication-methods

Jib not working when set to pom is indeed... weird... see also https://github.com/GoogleContainerTools/jib/issues/2533.

OTOH Jib seems to do some smarter stuff when packaging is war (using a embedded Jar), but not tested how this would work for two wars (server and workbench) ... https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#war-projects

**Comment by jeenbroekstra** [comment]
Random thought: should we put this plugin into the rdf4j-workbench and/or rdf4j-server modules, instead of in its own assembly module?

**Comment by barthanssens** [comment]
Hmz, to create separate images for workbench and server ? Could be very useful, especially for the server...

Haven't tested if Jib allows to bundle multiple war's when the packaging is set to war: looks like Jib uses a distroless Jetty, so I have to test it...

**Comment by jeenbroekstra** [comment]
@barthanssens this has been sitting idle for a while, is it still on your radar?

**Comment by barthanssens** [comment]
Well, given that the deployment is now much smoother thanks to the scripts Havard and you have written, it's not that useful anymore, so I'll close it

**Pull request closed without merging**
