### PR TITLE
GH-1685 subclassof inferencer bug

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #1685  

Briefly describe the changes proposed in this PR:

* added regression test that demonstrates the problem

### CODE REVIEW

**Comment by hmottestad** [comment]
I think this solution makes the code easier to understand. There is however a rather large performance regression which needs to be looked into.

In `ReasoningBenchmark` method `forwardChainingSchemaCachingRDFSInferencerMultipleTransactions` with param `"moreRdfs::12180"` the master branch shows 85 ms per operation, while this branch shows 600 ms per opertion. So roughly 7x slower. 

I've added a class for you to run the benchmark yourself: https://github.com/eclipse/rdf4j/blob/1dc0252f299e5eae927ee12f65dc8ff4f66834c3/testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/Main.java

**Comment by jeenbroekstra** [comment]
Performance regression is likely caused by the additional check in`statementAdded`. I think we can eliminate that and instead change the boolean flag as part of `processSchemaStatement`

**Comment by hmottestad** [comment]
LGTM - performance is good now :)

**Comment by hmottestad** [comment]
I've also downgraded the JMH version. I can make a new issue for upgrading it.

**Pull request merged**
