### PR TITLE
Changed USING to FROM

### PR DESCRIPTION
**Pull request by barthanssens**
This PR addresses GitHub issue: #439  .

Briefly describe the changes proposed in this PR:

* Use "FROM" and "FROM NAMED" instead of "USING"

I assume this is the only changed that is needed, since the (old) ticket mentions it is a "good first issue", so I guess this is the only trivial change that was required ?

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
@rdf4j-bot run tests

**Comment by jeenbroekstra** [comment]
@barthanssens there are a number of failing tests in the JsonLdParser - I don't see how that could be caused by this PR though.

**Comment by jeenbroekstra** [comment]
Ah, in fact the master branch is currently unstable. Looks like this was caused by the jsonld version bump. See https://ci.eclipse.org/rdf4j/job/rdf4j-client-master-verify/86/

**Comment by barthanssens** [comment]
My bad, I’ll take a look at it…

**Comment by barthanssens** [comment]
@rdf4j-bot run tests

**Pull request merged**
