### PR TITLE
GH-3504: security upgrade of log4j-core

### PR DESCRIPTION
**Pull request by barthanssens**
Signed-off-by: Bart Hanssens <bart.hanssens@bosa.fgov.be>

GitHub issue resolved: #3504 

Briefly describe the changes proposed in this PR:

- upgrade dependency to 2.15 to fix vulnerability 

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Review by jeenbroekstra — APPROVED** [review]
LGTM. @barthanssens you want to run a patch release straightaway?

**Review by jeenbroekstra — COMMENTED** [review]
I've just noticed that this _only_ bumps the version of log4j-core, not of log4j-api, log4j-slf4j-impl, or log4j-to-slf4j (which are referenced transitively in various modules, including the solr, elasticsearch, and lucene sails). Should we make sure we bump all of those to get things in sync? 

EDIT: actually just read the CVE and it looks like it's specifically log4j-core that's affected. So let's get this merged and released first and look at the other deps later.

**Comment by barthanssens** [comment]
The API jar might actually be ok (see last comment on https://issues.apache.org/jira/browse/LOG4J2-3201), but to be sure (and to make things a bit cleaner, it should indeed be better to bump everything log4j-related...)

**Comment by jeenbroekstra** [comment]
Just taking a closer look at the parts of RDF4J affected - it doesn't look like this directly affects anything we distribute, they're only test dependencies correct? If so, perhaps an immediate patch release is unnecessary.

**Comment by barthanssens** [comment]
Indeed, looks like it's not part of jar/wars we distribute, so probably not needed right away...

**Pull request merged**
