### PR TITLE
GH-2918 switch to CachedThreadPool to avoid deadlocks in interdependent queries

### PR DESCRIPTION
**Pull request by jeenbroekstra**
GitHub issue resolved: #2918 

Briefly describe the changes proposed in this PR:

- switch to CachedThreadPool executor since it has better behavior for spawning new threads as needed
- allow core threads to be terminated when keepAlive timeout has passed to conserve resources
- RDF4JProtocolSession uses a separate scheduled executor specifically for its transaction ping functionality
- added regression test

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits down to one or a few meaningful commits
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

### CODE REVIEW

**Comment by hmottestad** [comment]
Can you make a test that has 8 "subqueries" (nested 8 levels) so we know that we are fixing the underlying issue of how our code handles asynchronous execution?

**Comment by jeenbroekstra** [comment]
> Can you make a test that has 8 "subqueries" (nested 8 levels) so we know that we are fixing the underlying issue of how our code handles asynchronous execution?

No. Because we already know that that will fail, unless the core pool size is further upped.

**Comment by jeenbroekstra** [comment]
I had another look at this and I'm starting to think that switching to a CachedThreadPoolExecutor might actually be a better solution after all.

**Comment by jeenbroekstra** [comment]
Unless I receive any objections I'll merge this by the end of the day.

**Comment by hmottestad** [comment]
Does it fix the underlying design issue so that users can have unlimited nesting of queries?

**Comment by jeenbroekstra** [comment]
> Does it fix the underlying design issue so that users can have unlimited nesting of queries?

Not unlimited no - there is an upper limit to the number of concurrent threads a CachedThreadPool can support (at most Integer.MAX_VALUE though in practice you're more likely to hit resource boundaries first of course). But for all practical purposes that is good enough. 

In contrast to a ScheduledExecutor service, a Cached executor service does not queue jobs to wait for an existing thread to become available - it either grabs an existing available thread or immediately spawns a new one to execute the job. So it will never block to wait, and the deadlock situation can never occur, even with a large number of nested queries.

**Comment by hmottestad** [comment]
> > Does it fix the underlying design issue so that users can have unlimited nesting of queries?
> 
> Not unlimited no - there is an upper limit to the number of concurrent threads a CachedThreadPool can support (at most Integer.MAX_VALUE though in practice you're more likely to hit resource boundaries first of course). But for all practical purposes that is good enough.
> 
> In contrast to a ScheduledExecutor service, a Cached executor service does not queue jobs to wait for an existing thread to become available - it either grabs an existing available thread or immediately spawns a new one to execute the job. So it will never block to wait, and the deadlock situation can never occur, even with a large number of nested queries.

That’s the definition of unlimited in computer science.

**Pull request merged**
