### PR TITLE
GH-4265: update spring and springboot

### PR DESCRIPTION
**Pull request by barthanssens**
Signed-off-by: Bart Hanssens <bart.hanssens@bosa.fgov.be>

GitHub issue resolved: #4265 

Briefly describe the changes proposed in this PR:

- updated spring framework version
- updated spring boot version, to align versions of spring framework

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
New tool replacing IPZilla. 

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/tree/master/curations/maven/mavencentral/org.springframework.boot

A few components are already approved. Looks like it's mostly 2.7.5. If they cover all the components that we are using then maybe we could update to 2.7.5 instead?

**Comment by barthanssens** [comment]
Ah, good catch, 2.7.5 is also using spring framework 5.3.23 (and latest jackson-databind), that would definitely help

**Comment by barthanssens** [comment]
Only 2 dependencies need additional review, on it

**Comment by hmottestad** [comment]
Is this ready to merge @barthanssens ?

**Comment by barthanssens** [comment]
Yes, was just waiting for some tests to finish

**Pull request merged**
