### PR TITLE
Merge master -> develop

### PR DESCRIPTION
**Pull request by hmottestad**
Merge master -> develop

### CODE REVIEW

**Comment by hmottestad** [comment]
Thought i would sync develop with master for the main repo too. Although here it looks like someone has missed something wrt. the eclipse license bot. @jeenbroekstra  @barthanssens

**Comment by hmottestad** [comment]
Same build issue now: 

```
08:42:44.519 [main] WARN  FAILED BlockingChannelConnector@localhost:18080: java.net.BindException: Address already in use
08:42:44.519 [main] WARN  FAILED org.eclipse.jetty.server.Server@5b444398: java.net.BindException: Address already in use
```

**Comment by barthanssens** [comment]
> Thought i would sync develop with master for the main repo too. Although here it looks like someone has missed something wrt. the eclipse license bot. @jeenbroekstra @barthanssens

The bot mentions a "noreply" email address, I guess @jeenbroekstra can fix this manually as project lead

**Comment by jeenbroekstra** [comment]
I'll have a closer look tonight but it looks like  a bug in the validation bot rather than an actual problem with some of our commits. If so I can override and merge.

**Pull request merged**
