### PR TITLE
Fixed whitespace handling in rdf/xml.

### PR DESCRIPTION
**Pull request by pulquero**
This PR addresses GitHub issue: #213 

Briefly describe the changes proposed in this PR:

- ...
- ...
- ...

Make sure you've followed the [Contributor Guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md). In particular (please tick to indicate you've taken care of it):

- [x] RDF4J code formatting has been applied
- [x] tests are included
- [x] all tests succeed

Signed-off-by: Mark Hale <mark.hale@physics.org>

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
What issue is linked with this?

**Comment by jeenbroekstra** [comment]
Approved.

**Comment by ansell** [comment]
Is there a reason that the test case is attached as a ZIP (binary) file and not a text file?

**Comment by ansell** [comment]
Ie, if the test case was attached as a text file we could review what changes were made to it. It is simple to programattically generate a ZIP file for the test itself but difficult to use Git to review the pull request this way.

**Comment by jeenbroekstra** [comment]
Hadn't spotted that and went ahead and merged, but good point @ansell. I assume it is because @pulquero adapted an existing unit test (which uses a zip file) instead of writing a separate test. Which is perhaps not ideal, but on the other hand not a huge problem either IMO.

**Comment by pulquero** [comment]
Yes, I added an extra test case to the existing rdf parser test. Essentially I added some additional xml elements that included text with trailing spaces.
 

    On Tuesday, 5 July 2016, 23:36, Jeen Broekstra <notifications@github.com> wrote:
 

 Hadn't spotted that and went ahead and merged, but good point @ansell. I assume it is because @pulquero adapted an existing unit test (which uses a zip file) instead of writing a separate test. Which is perhaps not ideal, but on the other hand not a huge problem either IMO.—

**Pull request merged**
