### PR TITLE
GH-2324 blank node inlining still doesn't work

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #2324 

Briefly describe the changes proposed in this PR:

---- 
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [ ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra 

I now believe that the only way to properly fix this is to add control for if:
 1. only subject should be inlined
 1. only object should be inlined
 1. both should be inlined

**Comment by jeenbroekstra** [comment]
I think we need to step back a bit. ArrangedWriter has become a rather convoluted mess and the logic around inlining is spread out, which is really not good - the role of ArrangedWriter should really only be to buffer and sort statements, I think. Or perhaps we should get rid of it completely and just roll the arranging/inlining logic completely into the TurtleWriter class itself.

**Comment by jeenbroekstra** [comment]
Let's think about it: when can a blank node be inlined? Or actually, let's turn it around: when can a blank node _not_ be inlined?

As far as I'm aware the only real case in which a blank node can not be inlined is **if it is an object value for more than one statement.**, because in that case Turtle syntax needs to be able to refer to the same resource in multiple places. 

So that leaves us, I think, with a rather simple internal sorting algorithm: group all statements by subject then predicate. Sort subject groups such that subject blank nodes which also occur elsewhere as objects are ordered _directly after_ their object-occurrences. All blank nodes can no be handled as inlined with the exception of subjects that occur as objects in multiple places. Which is a simple check to make if we just buffer the entire model.

The only downside is that we will need to buffer the complete RDF document, but this is inevitable when we want blank node inlining.

**Comment by jeenbroekstra** [comment]
What complicates matters a bit is that ArrangedWriter also handles sorting logic related to other pretty-printing objectives, and I suspect this is why it's there in the first place: to allow disabling blank node inlining but still pretty-printing turtle without the need for full model buffering.

**Comment by jeenbroekstra** [comment]
I'm going to be tinkering with this a bit. I'm also toying with just rolling back the changes done for GH-1079 and looking at an alternative approach for that corner case.

**Comment by jeenbroekstra** [comment]
I've pushed a new branch with a proposed somewhat radical fix for the inlining problems: removing ArrangedWriter from the equation completely. See #2414

**Pull request closed without merging**
