### PR TITLE
GH-2189 code cleanup

### PR DESCRIPTION
**Pull request by barthanssens**
GitHub issue resolved: #2189

Briefly describe the changes proposed in this PR:

* Remove unused imports
* Use diamond operator
* Add missing Override annotations

---- 
PR Author Checklist: 

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
 - [x] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more details.

### CODE REVIEW

**Comment by barthanssens** [comment]
No code changes, just a bit of cleanup

**Comment by hmottestad** [comment]
Looks great :) Github CI is happy.

**Comment by hmottestad** [comment]
If you are cleaning up develop, can you do the same to master? So we don’t get lots of conflicts next time master is merged into develop.

**Comment by barthanssens** [comment]
Sure, I'll wait until _after_ the 3.2 release though ;-)
Just a series of Inspect'n'Transform checks in Netbeans, so it's not much work.

**Comment by hmottestad** [comment]
> Sure, I'll wait until _after_ the 3.2 release though ;-)
> Just a series of Inspect'n'Transform checks in Netbeans, so it's not much work.

I presume we will be merging develop into master for that. So then no need.

**Pull request merged**
